using Test
using AgentProviders

# The single home for wrapper-stripping, previously duplicated in BonitoWorker
# (`strip_injected_context`) and BonitoAgents (`meaningful_title`). The copies
# had already drifted: the server's grew support for tag attributes and
# self-closing tags, the worker's did not, so worker-side session previews
# leaked `<ide_selection file="…">` in full. Every attribute / self-closing
# case below is a regression test for that drift.

const CLAUDE = ClaudeCodeAgent()

@testset "meaningful_prompt (Claude)" begin
    @testset "wholly injected → nothing" begin
        @test meaningful_prompt(CLAUDE, "<ide_opened_file>The user opened /x/a.md in the IDE.</ide_opened_file>") === nothing
        @test meaningful_prompt(CLAUDE, "Caveat: The messages below were generated by the user while running local commands. DO NOT respond") === nothing
        @test meaningful_prompt(CLAUDE, "<command-name>/compact</command-name><command-message>compact</command-message>") === nothing
        @test meaningful_prompt(CLAUDE, "<system-reminder>As you answer…</system-reminder>") === nothing
        @test meaningful_prompt(CLAUDE, "   ") === nothing
        @test meaningful_prompt(CLAUDE, "") === nothing
    end

    @testset "unknown / future tags are stripped generically" begin
        @test meaningful_prompt(CLAUDE, "<local-command-caveat>Caveat: …</local-command-caveat>") === nothing
        @test meaningful_prompt(CLAUDE, "<future_unknown_wrapper>noise</future_unknown_wrapper>") === nothing
    end

    @testset "bare opener with no closer is commentary" begin
        @test meaningful_prompt(CLAUDE, "<ide_selection>The user selected lines 1 to 227 …") === nothing
        @test meaningful_prompt(CLAUDE, "<ide_opened_file>The user opened /x/a.md") === nothing
        @test meaningful_prompt(CLAUDE, "<system-reminder kind=\"foo\">no closer here") === nothing
    end

    @testset "prose survives, leading blocks are peeled" begin
        @test meaningful_prompt(CLAUDE, "fix the parser bug") == "fix the parser bug"
        @test meaningful_prompt(CLAUDE, "<ide_selection>lines 1-2</ide_selection>Ich arbeite am Plan!") == "Ich arbeite am Plan!"
        @test meaningful_prompt(CLAUDE, "<ide_opened_file>opened X</ide_opened_file>\n\nrun the tests") == "run the tests"
        @test meaningful_prompt(CLAUDE, "<local-command-caveat>x</local-command-caveat><ide_opened_file>y</ide_opened_file>do the thing") == "do the thing"
    end

    # These are the cases the worker copy got wrong: it bailed at the first
    # space in the opener and leaked the whole tag into the preview.
    @testset "tag attributes" begin
        @test meaningful_prompt(CLAUDE, "<command-args foo=\"x\">y</command-args>the real prompt") == "the real prompt"
        @test meaningful_prompt(CLAUDE, "<ide_selection file=\"a.jl\">lines 1-2</ide_selection>fix the parser bug") == "fix the parser bug"
    end

    @testset "self-closing tags" begin
        @test meaningful_prompt(CLAUDE, "<command-args/>\nthe rest") == "the rest"
        @test meaningful_prompt(CLAUDE, "<command-args foo=\"x\"/>\nthe rest") == "the rest"
        @test meaningful_prompt(CLAUDE, "<a/><b>y</b><c/>real") == "real"
    end
end

# The peel is aggressive by design (any leading `<tag>…</tag>`), which is only
# safe for a provider that actually injects such wrappers. A provider that
# injects nothing must keep the user's leading markup.
@testset "non-injecting providers keep leading markup" begin
    html = "<div>foo</div> why does this not render?"
    @test meaningful_prompt(OpenCodeAgent(), html) == html
    @test meaningful_prompt(MiMoAgent(), html) == html
    @test meaningful_prompt(OpenCodeAgent(), "  spaced  ") == "spaced"
    @test meaningful_prompt(OpenCodeAgent(), "   ") === nothing
    # Claude, by contrast, treats that leading block as a wrapper.
    @test meaningful_prompt(CLAUDE, html) == "why does this not render?"
end

@testset "strip_injected_context returns a String, never nothing" begin
    @test strip_injected_context(CLAUDE, "<a>x</a>real") == "real"
    @test strip_injected_context(CLAUDE, "<a>x</a>") == ""
    @test strip_injected_context(OpenCodeAgent(), "<a>x</a>real") == "<a>x</a>real"
end
