# ── Accounts, invites, worker credentials ────────────────────────────────────
# Behind the proxy the server owns what Caddy and Authelia know about machines
# and people (identity.jl): the worker credentials, rendered into the Caddyfile,
# and the accounts, rendered into Authelia's users database. It also decides
# which agent adapters workers keep installed. This file keeps those records,
# pushes them into the proxy's config, serves the invite pages, and draws the
# account controls on the dashboard. Nothing here checks a password: Caddy and
# Authelia do.
#
# Passwords are the server's alone. Authelia's own "reset password" and "change
# password" would write the users database behind the server's back, so the
# installer turns them off; a password is generated by Authelia (`--random`) and
# handed out once: to an admin, to a new account on its invite page, or to
# someone who asks for a new one on their account card.

credentials_file(s::ServerState) = joinpath(s.state_dir, "worker_credentials.json")
accounts_file(s::ServerState)    = joinpath(s.state_dir, "accounts.json")
invites_file(s::ServerState)     = joinpath(s.state_dir, "invites.json")

# Records of one kind from a JSON list; a malformed entry is skipped, not fatal.
function load_records!(into::AbstractDict, path::AbstractString, label::AbstractString, T::Type)
    raw = load_json_tolerant(String(path), label)
    raw === nothing && return nothing
    for d in raw
        try
            r = T(d)
            into[record_key(r)] = r
        catch e
            (e isa KeyError || e isa MethodError || e isa ArgumentError) || rethrow()
            @warn "skipping malformed entry in $(label)" exception = e
        end
    end
    return nothing
end

load_worker_credentials!(s::ServerState) =
    load_records!(s.worker_credentials[], credentials_file(s), "worker_credentials.json", WorkerCredential)
load_accounts!(s::ServerState) =
    load_records!(s.accounts[], accounts_file(s), "accounts.json", Account)
load_invites!(s::ServerState) =
    load_records!(s.invites[], invites_file(s), "invites.json", Invite)

save_worker_credentials!(s::ServerState) = lock(s.lock) do
    atomic_write_json(credentials_file(s), [Dict(c) for c in values(s.worker_credentials[])]; mode = 0o600)
end
save_accounts!(s::ServerState) = lock(s.lock) do
    atomic_write_json(accounts_file(s), [Dict(a) for a in values(s.accounts[])]; mode = 0o600)
end
save_invites!(s::ServerState) = lock(s.lock) do
    atomic_write_json(invites_file(s), [Dict(i) for i in values(s.invites[])]; mode = 0o600)
end

proxy_config(auth::ProxyAuth) = auth.config
proxy_config(::LocalAuth) =
    error("this server has no proxy in front (no proxy.json): there are no accounts or worker credentials to manage")

# Authelia's files live together, beside its users database. Without mail it
# writes what it would send (the one-time code that confirms a new second factor)
# to the notifications file.
notifications_file(cfg::ProxyConfig)   = joinpath(dirname(cfg.users_file), "notifications.txt")
authelia_config_file(cfg::ProxyConfig) = joinpath(dirname(cfg.users_file), "configuration.yml")

# Authelia's secrets, made once and kept in the state dir: a new session secret
# would log everyone out, a new storage key would leave its database unreadable.
authelia_secrets(state_dir::AbstractString) = (
    jwt     = bytes2hex(load_or_create_secret(state_dir, "authelia_jwt_secret")),
    session = bytes2hex(load_or_create_secret(state_dir, "authelia_session_secret")),
    storage = bytes2hex(load_or_create_secret(state_dir, "authelia_storage_key")))

smtp_settings(state_dir::AbstractString) =
    isfile(smtp_file(state_dir)) ? JSON.parsefile(smtp_file(state_dir)) : nothing

"""
    apply_proxy!(state)

Behind the proxy: write the Caddyfile, Authelia's users database and Authelia's
configuration from the server's records. Caddy (running with `--watch`) and
Authelia (watching its users file) reread the first two when they change; the
configuration only changes with `proxy.json`, which the installer follows with
a restart. A Caddyfile Caddy would reject is not written: it keeps serving the
last good one, and the error reaches whoever changed it. Without the proxy there
is nothing to do.
"""
apply_proxy!(state::ServerState) = apply_proxy!(state.auth, root_state(state))
apply_proxy!(::LocalAuth, ::ServerState) = nothing

function apply_proxy!(auth::ProxyAuth, root::ServerState)
    cfg = auth.config
    caddyfile, users = lock(root.lock) do
        (render_caddyfile(auth, values(root.worker_credentials[])),
         render_users_yaml(values(root.accounts[])))
    end
    candidate = cfg.caddyfile * ".new"
    atomic_write(io -> write(io, caddyfile), candidate; mode = 0o600)
    try
        check_caddyfile(cfg, candidate)
    catch
        rm(candidate; force = true)
        rethrow()
    end
    mv(candidate, cfg.caddyfile; force = true)
    atomic_write(io -> write(io, users), cfg.users_file; mode = 0o600)
    authelia = render_authelia_config(cfg, authelia_secrets(root.state_dir), smtp_settings(root.state_dir))
    atomic_write(io -> write(io, authelia), authelia_config_file(cfg); mode = 0o600)
    return nothing
end

# ── Worker credentials ───────────────────────────────────────────────────────

"""
    add_worker_credential!(state, owner) -> String

Issue a worker credential for `owner` ("Add worker"): Caddy checks it on `/w`
from now on. Returns `name:password`, the only time the password exists outside
its hash; the install command carries it to the new machine.
"""
function add_worker_credential!(state::ServerState, owner::AbstractString)
    root = root_state(state)
    cfg = proxy_config(root.auth)
    name = "w-" * bytes2hex(rand(Random.RandomDevice(), UInt8, 4))
    password = bytes2hex(rand(Random.RandomDevice(), UInt8, 24))
    cred = WorkerCredential(name, caddy_hash(cfg, password), String(owner), now(UTC))
    lock(root.lock) do
        root.worker_credentials[][name] = cred
        save_worker_credentials!(root)
    end
    apply_proxy!(root)
    safe_notify!(root.worker_credentials)
    @info "worker credential issued" name owner
    return name * ":" * password
end

"""
    revoke_worker_credential!(state, name) -> Bool

Take a worker credential back: Caddy refuses it from now on, and a worker that
is connected with it is disconnected (its reconnect meets the refusal).
"""
function revoke_worker_credential!(state::ServerState, name::AbstractString)
    root = root_state(state)
    removed = lock(root.lock) do
        c = pop!(root.worker_credentials[], String(name), nothing)
        c === nothing || save_worker_credentials!(root)
        c
    end
    removed === nothing && return false
    apply_proxy!(root)
    safe_notify!(root.worker_credentials)
    for (wid, w) in lock(() -> collect(root.workers[]), root.lock)
        w.credential == name || continue
        link = worker_link(root, wid)
        link === nothing || WorkerLink.kill!(link, "the worker's credential was revoked")
    end
    @info "worker credential revoked" name
    return true
end

# ── Accounts ─────────────────────────────────────────────────────────────────

# Change the accounts, then persist them and hand them to Authelia.
function update_accounts!(f::Function, state::ServerState)
    root = root_state(state)
    proxy_config(root.auth)
    lock(root.lock) do
        f(root.accounts[])
        save_accounts!(root)
    end
    apply_proxy!(root)
    safe_notify!(root.accounts)
    return nothing
end

function account(state::ServerState, name::AbstractString)
    a = lock(() -> get(root_state(state).accounts[], String(name), nothing), state.lock)
    a === nothing && error("there is no account '$(name)'")
    return a
end

# The server must keep an admin who can log in, and nobody locks themselves out.
function check_admin_remains(state::ServerState, name::AbstractString)
    state.user !== nothing && state.user.name == name &&
        error("you cannot do that to your own account")
    others = lock(state.lock) do
        count(a -> a.name != name && is_admin(a) && !a.disabled, values(root_state(state).accounts[]))
    end
    others == 0 && error("'$(name)' is the last admin who can log in")
    return nothing
end

"""
    add_account!(state, name; display_name, email, groups) -> String

A new login in `groups` ("admins" makes an admin), accepted by Authelia once it
rereads its users database (it watches the file). Returns the account's
password, generated by Authelia, for its owner; it exists nowhere else.
"""
function add_account!(state::ServerState, name::AbstractString;
                      display_name::AbstractString = name, email::AbstractString = "",
                      groups::Vector{String} = String[])
    cfg = proxy_config(state.auth)
    valid_name(name) ||
        error("an account name is letters, digits, '.', '_' and '-' (got '$(name)')")
    haskey(root_state(state).accounts[], name) && error("there is an account '$(name)' already")
    pw = authelia_random_password(cfg)
    acct = Account(String(name), isempty(display_name) ? String(name) : String(display_name),
                   String(email), groups, false, pw.hash)
    update_accounts!(state) do accounts
        # Checked again under the lock: two requests for one name, one account.
        haskey(accounts, acct.name) && error("there is an account '$(acct.name)' already")
        accounts[acct.name] = acct
    end
    @info "account added" name groups
    return pw.password
end

"A new random password for `name`, generated by Authelia; returned once."
function reset_account_password!(state::ServerState, name::AbstractString)
    a = account(state, name)
    pw = authelia_random_password(proxy_config(state.auth))
    update_accounts!(_ -> (a.password_hash = pw.hash), state)
    return pw.password
end

"""
    set_account_disabled!(state, name, disabled)

Authelia refuses a disabled account's next request; its open tabs are closed here,
since an open websocket is never re-checked.
"""
function set_account_disabled!(state::ServerState, name::AbstractString, disabled::Bool)
    a = account(state, name)
    disabled && is_admin(a) && check_admin_remains(state, name)
    update_accounts!(_ -> (a.disabled = disabled), state)
    disabled && close_user_sessions!(state, name)
    return nothing
end

"""
    set_account_groups!(state, name, groups)

Put `name` in exactly `groups`. "admins" makes an admin; any other group is one
workers can be shared with (`share_worker!`).
"""
function set_account_groups!(state::ServerState, name::AbstractString, groups::Vector{String})
    a = account(state, name)
    is_admin(a) && !("admins" in groups) && check_admin_remains(state, name)
    update_accounts!(_ -> (a.groups = groups), state)
    # The groups arrive with the next request through Authelia: reload the tabs.
    close_user_sessions!(state, name)
    return nothing
end

set_account_admin!(state::ServerState, name::AbstractString, admin::Bool) =
    set_account_groups!(state, name, admin ? union(account(state, name).groups, ["admins"]) :
                                             setdiff(account(state, name).groups, ["admins"]))

function remove_account!(state::ServerState, name::AbstractString)
    a = account(state, name)
    is_admin(a) && check_admin_remains(state, name)
    state.user !== nothing && state.user.name == name && error("you cannot remove your own account")
    update_accounts!(accounts -> delete!(accounts, a.name), state)
    close_user_sessions!(state, name)
    return nothing
end

"Every group some account is in, sorted."
all_groups(state::ServerState) =
    sort!(unique!(String[g for a in values(root_state(state).accounts[]) for g in a.groups]))

# ── Invites ──────────────────────────────────────────────────────────────────

"""
    create_invite!(state, groups; valid_for = Day(7)) -> String

A link that lets one person create their own account in `groups`, valid for
`valid_for`. The link is returned here only; the server keeps its token's hash.
"""
function create_invite!(state::ServerState, groups::Vector{String}; valid_for::Period = Day(7))
    root = root_state(state)
    proxy_config(root.auth)
    token = bytes2hex(rand(Random.RandomDevice(), UInt8, 32))
    t = now(UTC)
    invite = Invite(invite_id(token), groups, acting_owner(state), t, t + valid_for)
    lock(root.lock) do
        filter!(((_, i),) -> i.expires > t, root.invites[])   # expired ones go with it
        root.invites[][invite.id] = invite
        save_invites!(root)
    end
    safe_notify!(root.invites)
    @info "invite created" groups by = invite.created_by expires = invite.expires
    return install_base_url(root) * "/invite/" * token
end

function revoke_invite!(state::ServerState, id::AbstractString)
    root = root_state(state)
    removed = lock(root.lock) do
        i = pop!(root.invites[], String(id), nothing)
        i === nothing || save_invites!(root)
        i
    end
    removed === nothing && return false
    safe_notify!(root.invites)
    return true
end

"The invite a link carries, while it is good for an account; `nothing` otherwise."
function open_invite(state::ServerState, token::AbstractString)
    i = lock(() -> get(root_state(state).invites[], invite_id(token), nothing), state.lock)
    return (i === nothing || i.expires <= now(UTC)) ? nothing : i
end

"""
    redeem_invite!(state, token, name; display_name, email) -> String

Create the account an invite link offers, and use the link up. Returns the new
account's password, which its owner sees once.
"""
function redeem_invite!(state::ServerState, token::AbstractString, name::AbstractString;
                        display_name::AbstractString = name, email::AbstractString = "")
    root = root_state(state)
    id = invite_id(token)
    # Taken out first, so two submissions of one link cannot make two accounts.
    invite = lock(() -> pop!(root.invites[], id, nothing), root.lock)
    invite === nothing && error("this invite link was used already or revoked")
    if invite.expires <= now(UTC)
        save_invites!(root)
        safe_notify!(root.invites)
        error("this invite link has expired")
    end
    password = try
        add_account!(root, name; display_name, email, groups = invite.groups)
    catch e
        # A name that is taken or not allowed: the link stays good for another try.
        lock(() -> (root.invites[][id] = invite), root.lock)
        rethrow()
    end
    save_invites!(root)
    safe_notify!(root.invites)
    @info "invite used" name invited_by = invite.created_by
    return password
end

# /invite/<token>: open to anyone (the token is the proof), so it is plain HTML
# with a form, no dashboard session.
const INVITE_ROUTE_RE = r"^/invite/([0-9a-f]{64})/?(?:$|\?)"

function add_invite_routes!(srv::Bonito.Server, state::ServerState)
    Bonito.route!(srv, INVITE_ROUTE_RE => function(context)
        invite_response(state.auth, state, context.request, String(context.match.captures[1]))
    end)
end

invite_response(::LocalAuth, state::ServerState, request, token::AbstractString) =
    invite_page(404, "Not found", "<p>This server has no accounts to invite anyone to.</p>")

function invite_response(auth::ProxyAuth, state::ServerState, request, token::AbstractString)
    open_invite(state, token) === nothing && return invite_page(404, "This invite is not valid",
        "<p>The link was used already, revoked, or has expired. Ask for a new one.</p>")
    request.method == "POST" ||
        return invite_page(200, "Create your account", invite_form(Dict{String,String}(), ""))
    form = form_fields(String(request.body))
    name = strip(get(form, "name", ""))
    display_name = strip(get(form, "display_name", ""))
    password = try
        redeem_invite!(state, token, name; display_name = isempty(display_name) ? name : display_name,
                       email = strip(get(form, "email", "")))
    catch e
        (e isa ErrorException || e isa ProcessFailedException || e isa Base.IOError) || rethrow()
        return invite_page(400, "Create your account",
                           invite_form(form, first(split(sprint(showerror, e), '\n'))))
    end
    cfg = auth.config
    second_factor = cfg.smtp ?
        "Authelia emails you a code to confirm it." :
        "Authelia confirms it with a one-time code; this server sends no mail, so ask an admin for it."
    return invite_page(200, "Your account is ready", """
        <p>Account <b>$(esc_html(name))</b>. Your password, shown only now:</p>
        <p><code class="pw">$(esc_html(password))</code></p>
        <p>Store it in your password manager, then <a href="$(esc_html(public_origin(cfg, cfg.domain)))">log in</a>.
        At the first login you set up a second factor (an authenticator app or a security key).
        $(second_factor)</p>""")
end

function invite_form(form::AbstractDict, error_message::AbstractString)
    field(key, label, type = "text") = """
        <label>$(label)<input type="$(type)" name="$(key)" value="$(esc_html(get(form, key, "")))"></label>"""
    err = isempty(error_message) ? "" : "<p class=\"err\">$(esc_html(error_message))</p>"
    return """
        $(err)
        <form method="post">
        $(field("name", "Account name (letters, digits, '.', '_', '-')"))
        $(field("display_name", "Full name"))
        $(field("email", "Email", "email"))
        <button type="submit">Create account</button>
        </form>"""
end

function invite_page(status::Int, title::AbstractString, body::AbstractString)
    html = """<!doctype html><html><head><meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>$(esc_html(title))</title><style>
        body { font-family: system-ui, sans-serif; background: #f5f5f4; color: #1c1917; }
        main { max-width: 30rem; margin: 4rem auto; padding: 2rem; background: #fff; border-radius: 10px; }
        label { display: block; margin: 0.8rem 0; font-size: 0.9rem; }
        input { display: block; width: 100%; box-sizing: border-box; margin-top: 0.3rem; padding: 0.5rem;
                border: 1px solid #d6d3d1; border-radius: 6px; font-size: 1rem; }
        button { margin-top: 1rem; padding: 0.6rem 1.2rem; border: 0; border-radius: 6px;
                 background: #1c1917; color: #fff; font-size: 1rem; cursor: pointer; }
        .err { color: #b91c1c; }
        .pw { font-size: 1.2rem; padding: 0.3rem 0.5rem; background: #f5f5f4; user-select: all; }
        </style></head><body><main><h1>$(esc_html(title))</h1>$(body)</main></body></html>"""
    # The token is in the URL: no Referer carries it anywhere, nothing caches it.
    return HTTP.Response(status, ["Content-Type" => "text/html; charset=utf-8",
                                  "Cache-Control" => "no-store", "Referrer-Policy" => "no-referrer"];
                         body = html)
end

# An `application/x-www-form-urlencoded` body: `+` is a space there.
function form_fields(body::AbstractString)
    fields = Dict{String,String}()
    for pair in split(body, '&'; keepempty = false)
        k, v = occursin('=', pair) ? split(pair, '='; limit = 2) : (pair, "")
        fields[HTTP.unescapeuri(replace(k, '+' => ' '))] = HTTP.unescapeuri(replace(v, '+' => ' '))
    end
    return fields
end

# ── Who sees what ────────────────────────────────────────────────────────────

"""
    visible(state, chat_or_worker) -> Bool

May the person `state` serves see this chat or worker? Admins see everything,
members what they own, and the workers shared with a group they are in. The
server's own view (no user) sees everything.
"""
visible(state::ServerState, x) = visible(state.user, x)
visible(::Nothing, x) = true
visible(user::User, p::ProjectInfo) = is_admin(user) || p.owner == user.name
visible(user::User, w::WorkerInfo) =
    is_admin(user) || w.owner == user.name || !isdisjoint(w.shared_with, user.groups)

"Does `state` serve an admin? The server's own view (no user) acts as one."
is_admin(state::ServerState) = state.user === nothing || is_admin(state.user)

"May the person `state` serves rename, update, share or remove this worker?"
can_manage(state::ServerState, w::WorkerInfo) = can_manage(state.user, w)
can_manage(::Nothing, w::WorkerInfo) = true
can_manage(user::User, w::WorkerInfo) = is_admin(user) || w.owner == user.name

"""
    share_worker!(state, worker_id, groups)

Let the members of `groups` see the worker and start chats on it. Sharing a
worker shares its machine: their agents run there as the worker's user.
"""
function share_worker!(state::ServerState, worker_id::AbstractString, groups::Vector{String})
    root = root_state(state)
    lock(root.lock) do
        w = get(root.workers[], String(worker_id), nothing)
        w === nothing && error("there is no worker '$(worker_id)'")
        w.shared_with = groups
        save_workers!(root)
    end
    notify_workers!(root)
    @info "worker shared" worker_id groups
    return nothing
end

# Live browser sessions by user, so disabling an account can end them.
function register_user_session!(state::ServerState, session::Bonito.Session, user::User)
    root = root_state(state)
    lock(root.lock) do
        push!(get!(Vector{Bonito.Session}, root.user_sessions, user.name), session)
    end
    on(session.on_close) do closed
        closed || return
        lock(root.lock) do
            list = get(root.user_sessions, user.name, nothing)
            list === nothing || filter!(s -> s !== session, list)
        end
    end
    return nothing
end

function close_user_sessions!(state::ServerState, name::AbstractString)
    root = root_state(state)
    sessions = lock(() -> pop!(root.user_sessions, String(name), Bonito.Session[]), root.lock)
    foreach(close, sessions)
    return length(sessions)
end

# ── Agent adapters ───────────────────────────────────────────────────────────

"""
    set_harness_spec!(state, spec)

Change which agent adapters workers keep installed, and at which versions:
persisted, and sent to every connected worker right away (a worker that is
offline gets it with its next hello acknowledgement).
"""
function set_harness_spec!(state::ServerState, spec::Dict{String,Any})
    root = root_state(state)
    root.harness_spec[] = spec
    save_settings!(root)
    links = lock(() -> collect(root.worker_links), root.lock)
    for (wid, link) in links
        WorkerLink.state(link) === :connected || continue
        try
            send_command(root, wid, Dict("type" => "harness_spec", "spec" => spec))
        catch e
            # The worker dropped between the check and the send; its next hello
            # acknowledgement carries the spec.
            (e isa WebSockets.WebSocketError || e isa WorkerLink.LinkDead) || rethrow()
        end
    end
    return nothing
end

# ── Dashboard controls ───────────────────────────────────────────────────────

const AdminStyles = Bonito.Styles(
    CSS(".bt-admin-table",
        "width" => "100%", "border-collapse" => "collapse", "font-size" => "13px"),
    CSS(".bt-admin-table th, .bt-admin-table td",
        "text-align" => "left", "padding" => "6px 8px",
        "border-bottom" => "1px solid var(--bt-border)"),
    CSS(".bt-admin-table th",
        "color" => "var(--bt-text-faint)", "font-weight" => "600", "font-size" => "11px",
        "text-transform" => "uppercase", "letter-spacing" => "0.04em"),
    CSS(".bt-admin-actions",
        "display" => "flex", "gap" => "6px", "flex-wrap" => "wrap"),
    CSS(".bt-admin-form",
        "display" => "flex", "gap" => "8px", "flex-wrap" => "wrap", "align-items" => "center",
        "margin-top" => "10px"),
    CSS(".bt-admin-form input[type=text], .bt-admin-table input[type=text]",
        "padding" => "5px 8px", "border" => "1px solid var(--bt-border)",
        "border-radius" => "var(--bt-radius-sm)", "background" => "var(--bt-surface)",
        "color" => "var(--bt-text)", "font-size" => "13px"),
    CSS(".bt-admin-status",
        "font-size" => "12px", "color" => "var(--bt-text-muted)", "margin-top" => "8px"),
    CSS(".bt-admin-secret",
        "margin-top" => "10px", "user-select" => "all"),
    CSS(".bt-admin-muted",
        "color" => "var(--bt-text-muted)"),
    CSS(".bt-admin-pre",
        "white-space" => "pre-wrap", "font-size" => "12px", "max-height" => "240px",
        "overflow" => "auto", "margin-top" => "8px"),
)

# An action run from a button: `f()` returns a status line, or a failure the
# person should read (a name taken, the last admin, Caddy or Authelia refusing)
# is shown instead.
function admin_action!(status::Observable{String}, f::Function)
    msg = try
        f()
    catch e
        (e isa ErrorException || e isa ProcessFailedException || e isa Base.IOError ||
         e isa HTTP.Exceptions.HTTPError) || rethrow()
        @warn "account action failed" exception = (e, catch_backtrace())
        first(split(sprint(showerror, e), '\n'))
    end
    safe_set!(status, String(msg))
    return nothing
end

text_input(obs::Observable{String}, placeholder::AbstractString) =
    DOM.input(type = "text", placeholder = placeholder, value = obs,
              oninput = js"event => $(obs).notify(event.target.value)")

"""
    worker_install_block(::ProxyAuth, session, state)

"Add worker" behind the proxy: an admin issues a credential and gets the install
command that carries it (shown once); the credentials issued so far can be
revoked. A member is told to ask an admin.
"""
function worker_install_block(::ProxyAuth, session::Bonito.Session, state::ServerState)
    summary = DOM.summary(DOM.span("Add a worker"; class = "bt-discover-title");
                          class = "bt-discover-header")
    if !is_admin(state)
        return DOM.details(summary,
            DOM.div("An admin adds workers: each machine gets its own credential.";
                    class = "bt-install-block bt-admin-muted");
            class = "bt-card bt-install-details")
    end
    base = install_base_url(state)
    issued = Observable{Any}(DOM.div())
    status = Observable("")
    add = Observable(false)
    revoke = Observable("")
    on(session, add) do _
        admin_action!(status, () -> begin
            cred = add_worker_credential!(state, state.user.name)
            unix = "curl -fsSL $(base)/install.sh | BONITOAGENTS_WORKER_CREDENTIAL='$(cred)' sh"
            win  = "\$env:BONITOAGENTS_WORKER_CREDENTIAL='$(cred)'; irm $(base)/install.ps1 | iex"
            issued[] = DOM.div(
                DOM.div("Run this on the new machine. It carries the worker's credential, " *
                        "shown only now; revoking it below disconnects that worker.";
                        class = "bt-admin-muted"),
                install_command_row("Linux / macOS", unix),
                install_command_row("Windows (PowerShell)", win);
                class = "bt-admin-secret")
            "credential $(first(split(cred, ':'))) issued"
        end)
    end
    on(session, revoke) do name
        isempty(name) && return
        admin_action!(status, () ->
            revoke_worker_credential!(state, name) ? "revoked $(name)" : "$(name) was already gone")
    end
    creds = map(session, state.worker_credentials, state.workers) do creds, workers
        isempty(creds) && return DOM.div("No worker credentials issued yet."; class = "bt-admin-muted")
        rows = map(sort!(collect(values(creds)); by = c -> c.created)) do c
            used = [w.name for w in values(workers) if w.credential == c.name]
            DOM.tr(DOM.td(DOM.code(c.name)), DOM.td(isempty(used) ? "not connected yet" : join(used, ", ")),
                   DOM.td(c.owner), DOM.td(Dates.format(c.created, "yyyy-mm-dd")),
                   DOM.td(DOM.button("Revoke"; class = "bt-btn bt-btn-sm bt-btn-secondary",
                                     onclick = js"event => $(revoke).notify($(c.name))")))
        end
        DOM.table(DOM.tr(DOM.th("Credential"), DOM.th("Worker"), DOM.th("Issued by"),
                         DOM.th("Issued"), DOM.th("")), rows...; class = "bt-admin-table")
    end
    body = DOM.div(
        AdminStyles,
        DOM.button("Add worker"; class = "bt-btn bt-btn-sm",
                   onclick = js"event => $(add).notify(true)"),
        issued,
        DOM.div(status; class = "bt-admin-status"),
        creds;
        class = "bt-install-block")
    # `open` is a boolean attribute: present means open, whatever its value.
    return isempty(state.workers[]) ?
        DOM.details(summary, body; class = "bt-card bt-install-details", open = true) :
        DOM.details(summary, body; class = "bt-card bt-install-details")
end

"""
    account_sections(session, state)

The dashboard's account sections: everyone's own account behind the proxy, and
for admins the accounts, the invites and the agent adapter versions workers keep
installed.
"""
function account_sections(session::Bonito.Session, state::ServerState)
    state.user === nothing && return DOM.div()
    admin = is_admin(state)
    return DOM.div(AdminStyles,
                   own_account_section(state.auth, session, state),
                   admin ? accounts_section(state.auth, session, state) : DOM.div(),
                   admin ? invites_section(state.auth, session, state) : DOM.div(),
                   admin ? adapters_section(session, state) : DOM.div())
end

own_account_section(::LocalAuth, session::Bonito.Session, state::ServerState) = DOM.div()

function own_account_section(auth::ProxyAuth, session::Bonito.Session, state::ServerState)
    user = state.user
    cfg = auth.config
    status = Observable("")
    secret = Observable("")
    renew = Observable(false)
    on(session, renew) do _
        admin_action!(status, () -> begin
            secret[] = "Your new password, shown only now: " * reset_account_password!(state, user.name)
            "new password set"
        end)
    end
    groups = isempty(user.groups) ? "no groups" : "groups: " * join(user.groups, ", ")
    logout = public_origin(cfg, cfg.auth_domain) * "/logout?rd=" * HTTP.escapeuri(public_origin(cfg, cfg.domain))
    return DOM.div(
        DOM.div(DOM.h2("Your account"); class = "bt-section"),
        DOM.div(
            DOM.div("Signed in as $(user.display_name) ($(user.name)); $(groups)."),
            DOM.div(
                DOM.button("New password"; class = "bt-btn bt-btn-sm bt-btn-secondary",
                           onclick = js"""event => {
                               if (confirm("Replace your password with a new, generated one?"))
                                   $(renew).notify(true);
                           }"""),
                DOM.a("Log out"; href = logout, class = "bt-btn bt-btn-sm bt-btn-secondary");
                class = "bt-admin-form"),
            DOM.div(secret; class = "bt-admin-secret"),
            DOM.div(status; class = "bt-admin-status");
            class = "bt-card"))
end

accounts_section(::LocalAuth, session::Bonito.Session, state::ServerState) = DOM.div()

function accounts_section(auth::ProxyAuth, session::Bonito.Session, state::ServerState)
    status = Observable("")
    secret = Observable("")
    # [verb, account, argument] from a row's buttons and group field.
    action = Observable{Any}(nothing)
    new_name = Observable("")
    new_display = Observable("")
    new_email = Observable("")
    new_groups = Observable("")
    new_admin = Observable(false)
    shown(name, pw) = "Password for $(name), shown only now: $(pw)"
    on(session, action) do a
        a isa AbstractVector && length(a) == 3 || return
        verb, name, arg = String(a[1]), String(a[2]), String(a[3])
        admin_action!(status, () -> begin
            if verb == "add"
                groups = parse_groups(new_groups[])
                new_admin[] && union!(groups, ["admins"])
                pw = add_account!(state, new_name[]; display_name = new_display[],
                                  email = new_email[], groups)
                secret[] = shown(new_name[], pw)
                added = new_name[]
                new_name[] = ""; new_display[] = ""; new_email[] = ""; new_groups[] = ""
                "account $(added) added"
            elseif verb == "password"
                secret[] = shown(name, reset_account_password!(state, name))
                "new password for $(name)"
            elseif verb == "groups"
                set_account_groups!(state, name, parse_groups(arg)); "groups of $(name) saved"
            elseif verb == "disable"
                set_account_disabled!(state, name, true); "$(name) disabled; their open tabs were closed"
            elseif verb == "enable"
                set_account_disabled!(state, name, false); "$(name) enabled"
            elseif verb == "admin"
                set_account_admin!(state, name, true); "$(name) is an admin"
            elseif verb == "member"
                set_account_admin!(state, name, false); "$(name) is a member"
            elseif verb == "remove"
                remove_account!(state, name); "$(name) removed"
            else
                error("unknown account action '$(verb)'")
            end
        end)
    end
    act(verb, name) = js"event => $(action).notify([$(verb), $(name), ''])"
    table = map(session, state.accounts) do accounts
        rows = map(sort!(collect(values(accounts)); by = a -> a.name)) do a
            DOM.tr(
                DOM.td(a.name), DOM.td(a.display_name), DOM.td(a.email),
                DOM.td(DOM.input(type = "text", value = join(filter(!=("admins"), a.groups), ", "),
                                 placeholder = "groups",
                                 title = "Comma-separated; Enter saves. Workers can be shared with a group.",
                                 onkeydown = js"""event => {
                                     if (event.key === 'Enter')
                                         $(action).notify(['groups', $(a.name),
                                             event.target.value + ($(is_admin(a)) ? ', admins' : '')]);
                                 }""")),
                DOM.td(is_admin(a) ? "admin" : "member"),
                DOM.td(a.disabled ? "disabled" : "active"),
                DOM.td(DOM.div(
                    DOM.button(is_admin(a) ? "Make member" : "Make admin";
                               class = "bt-btn bt-btn-sm bt-btn-secondary",
                               onclick = act(is_admin(a) ? "member" : "admin", a.name)),
                    DOM.button(a.disabled ? "Enable" : "Disable";
                               class = "bt-btn bt-btn-sm bt-btn-secondary",
                               onclick = act(a.disabled ? "enable" : "disable", a.name)),
                    DOM.button("New password"; class = "bt-btn bt-btn-sm bt-btn-secondary",
                               onclick = act("password", a.name)),
                    DOM.button("Remove"; class = "bt-btn bt-btn-sm bt-btn-secondary",
                               onclick = js"""event => {
                                   if (confirm("Remove the account " + $(a.name) + "?"))
                                       $(action).notify(['remove', $(a.name), '']);
                               }""");
                    class = "bt-admin-actions")))
        end
        DOM.table(DOM.tr(DOM.th("Account"), DOM.th("Name"), DOM.th("Email"), DOM.th("Groups"),
                         DOM.th("Role"), DOM.th("Status"), DOM.th("")), rows...; class = "bt-admin-table")
    end
    form = DOM.div(
        text_input(new_name, "account name"), text_input(new_display, "full name"),
        text_input(new_email, "email"), text_input(new_groups, "groups"),
        DOM.label(DOM.input(type = "checkbox", checked = new_admin,
                            onchange = js"event => $(new_admin).notify(event.target.checked)"),
                  " admin"),
        DOM.button("Add account"; class = "bt-btn bt-btn-sm",
                   onclick = js"event => $(action).notify(['add', $(new_name).value, ''])");
        class = "bt-admin-form")
    return DOM.div(
        DOM.div(DOM.h2("Accounts"); class = "bt-section"),
        DOM.div(table, form, DOM.div(secret; class = "bt-admin-secret"),
                DOM.div(status; class = "bt-admin-status"),
                login_codes_block(auth.config, session);
                class = "bt-card"))
end

# Without mail, Authelia writes the one-time code that confirms someone's new
# second factor to a file on the server; admins read it here and pass it on.
login_codes_block(cfg::ProxyConfig, session::Bonito.Session) =
    cfg.smtp ? DOM.div() : login_codes_block(notifications_file(cfg), session)

function login_codes_block(file::AbstractString, session::Bonito.Session)
    shown = Observable("")
    refresh = Observable(false)
    on(session, refresh) do _
        safe_set!(shown, isfile(file) ? read(file, String) : "Nothing yet.")
    end
    return DOM.details(
        DOM.summary("Login codes (this server sends no mail)"),
        DOM.div("Setting up a second factor asks for a code Authelia would have mailed. " *
                "The latest one is here; pass it on to the person it names.";
                class = "bt-admin-muted"),
        DOM.button("Show the latest"; class = "bt-btn bt-btn-sm bt-btn-secondary",
                   onclick = js"event => $(refresh).notify(true)"),
        DOM.pre(shown; class = "bt-admin-pre"))
end

invites_section(::LocalAuth, session::Bonito.Session, state::ServerState) = DOM.div()

function invites_section(::ProxyAuth, session::Bonito.Session, state::ServerState)
    status = Observable("")
    link = Observable("")
    groups = Observable("")
    days = Observable("7")
    create = Observable(false)
    revoke = Observable("")
    on(session, create) do _
        admin_action!(status, () -> begin
            n = tryparse(Int, strip(days[]))
            (n === nothing || n < 1) && error("valid for: a number of days, at least 1")
            link[] = create_invite!(state, parse_groups(groups[]); valid_for = Day(n))
            "invite created; send the link to one person"
        end)
    end
    on(session, revoke) do id
        isempty(id) && return
        admin_action!(status, () -> revoke_invite!(state, id) ? "invite revoked" : "the invite was already gone")
    end
    table = map(session, state.invites) do invites
        open = sort!([i for i in values(invites) if i.expires > now(UTC)]; by = i -> i.created)
        isempty(open) && return DOM.div("No open invites."; class = "bt-admin-muted")
        rows = map(open) do i
            DOM.tr(DOM.td(i.created_by), DOM.td(isempty(i.groups) ? "member" : join(i.groups, ", ")),
                   DOM.td(Dates.format(i.created, "yyyy-mm-dd HH:MM")),
                   DOM.td(Dates.format(i.expires, "yyyy-mm-dd HH:MM")),
                   DOM.td(DOM.button("Revoke"; class = "bt-btn bt-btn-sm bt-btn-secondary",
                                     onclick = js"event => $(revoke).notify($(i.id))")))
        end
        DOM.table(DOM.tr(DOM.th("Invited by"), DOM.th("Groups"), DOM.th("Created (UTC)"),
                         DOM.th("Expires (UTC)"), DOM.th("")), rows...; class = "bt-admin-table")
    end
    return DOM.div(
        DOM.div(DOM.h2("Invites"); class = "bt-section"),
        DOM.div(
            DOM.div("An invite link lets one person create their own account; they get " *
                    "their password on the page it opens.";
                    class = "bt-admin-muted"),
            DOM.div(text_input(groups, "groups (\"admins\" for an admin)"),
                    DOM.label("valid for ", DOM.input(type = "text", value = days, size = 3,
                              oninput = js"event => $(days).notify(event.target.value)"), " days"),
                    DOM.button("Create invite link"; class = "bt-btn bt-btn-sm",
                               onclick = js"event => $(create).notify(true)");
                    class = "bt-admin-form"),
            DOM.div(link; class = "bt-admin-secret"),
            DOM.div(status; class = "bt-admin-status"),
            table;
            class = "bt-card"))
end

"""
    adapters_section(session, state)

Which agent adapters workers keep installed, at which versions ("latest", or a
version), on which Node ("lts", a major, or a version). Saving sends the change to
every connected worker; each installs it once no chat runs there.
"""
function adapters_section(session::Bonito.Session, state::ServerState)
    spec = state.harness_spec[]
    spec === nothing && return DOM.div()
    status = Observable("")
    node = Observable(String(spec["node"]))
    packages = Dict{String,Observable{String}}(String(k) => Observable(String(v))
                                               for (k, v) in spec["packages"])
    save = Observable(false)
    on(session, save) do _
        admin_action!(status, () -> begin
            new = Dict{String,Any}("node" => String(strip(node[])),
                                   "packages" => Dict{String,Any}(k => String(strip(o[])) for (k, o) in packages))
            (isempty(new["node"]) || any(isempty, values(new["packages"]))) &&
                error("every version needs a value: \"latest\" or a version")
            set_harness_spec!(state, new)
            "saved; connected workers install it once no chat runs there"
        end)
    end
    row(label, obs) = DOM.div(DOM.span(label; class = "bt-settings-title"),
                              DOM.input(type = "text", value = obs,
                                        oninput = js"event => $(obs).notify(event.target.value)");
                              class = "bt-admin-form")
    return DOM.div(
        DOM.div(DOM.h2("Agent adapters"); class = "bt-section"),
        DOM.div(
            DOM.div("Workers install these themselves, with a private Node, and update them " *
                    "while no chat runs. \"latest\" follows the npm registry.";
                    class = "bt-admin-muted"),
            row("Node", node),
            (row(k, packages[k]) for k in sort!(collect(keys(packages))))...,
            DOM.button("Save"; class = "bt-btn bt-btn-sm", onclick = js"event => $(save).notify(true)"),
            DOM.div(status; class = "bt-admin-status");
            class = "bt-card"))
end

"""
    worker_sharing_row(auth, session, state, worker_id)

Behind the proxy, on a worker's card: the groups it is shared with, editable by
whoever manages it.
"""
worker_sharing_row(::LocalAuth, session::Bonito.Session, state::ServerState, worker_id::String) = DOM.div()

function worker_sharing_row(::ProxyAuth, session::Bonito.Session, state::ServerState, worker_id::String)
    w = get(state.workers[], worker_id, nothing)
    (w === nothing || !can_manage(state, w)) && return DOM.div()
    status = Observable("")
    groups = Observable(join(w.shared_with, ", "))
    on(session, groups) do text
        admin_action!(status, () -> begin
            share_worker!(state, worker_id, parse_groups(text))
            isempty(strip(text)) ? "not shared" : "shared"
        end)
    end
    return DOM.div(
        DOM.span("Shared with"; class = "bt-admin-muted"),
        DOM.input(type = "text", value = groups, placeholder = "groups", size = 18,
                  title = "Comma-separated groups; Enter saves. Their members start chats here, " *
                          "which run as this machine's user.",
                  onkeydown = js"event => { if (event.key === 'Enter') $(groups).notify(event.target.value); }"),
        DOM.span(status; class = "bt-admin-status"), AdminStyles;
        class = "bt-admin-form")
end
