# ── Accounts, invites, worker credentials ────────────────────────────────────
# Behind the proxy or a tunnel the server owns what Authelia (and Caddy) know
# about machines and people (identity.jl): the accounts, rendered into Authelia's
# users database, and the worker credentials, rendered into the Caddyfile behind
# the proxy. It also decides which agent adapters workers keep installed. This
# file keeps those records, pushes them into the login's config, serves the
# invite pages, and draws the account controls on the dashboard. Nothing here
# checks a password: Authelia does (and Caddy, a worker's, behind the proxy).
#
# Passwords are the server's alone. Authelia's own "reset password" and "change
# password" would write the users database behind the server's back, so the
# installer turns them off; a password is generated by Authelia (`--random`) and
# handed out once: to an admin, to a new account on its invite page, or to
# someone who asks for a new one on their account card.

credentials_file(s::ServerState) = joinpath(s.state_dir, "worker_credentials.json")
accounts_file(s::ServerState)    = joinpath(s.state_dir, "accounts.json")
invites_file(s::ServerState)     = joinpath(s.state_dir, "invites.json")

# Records of one kind from a JSON list; a malformed entry is skipped, not fatal.
function load_records!(into::AbstractDict, path::AbstractString, label::AbstractString, T::Type)
    raw = load_json_tolerant(String(path), label)
    raw === nothing && return nothing
    for d in raw
        try
            r = T(d)
            into[record_key(r)] = r
        catch e
            (e isa KeyError || e isa MethodError || e isa ArgumentError) || rethrow()
            @warn "skipping malformed entry in $(label)" exception = e
        end
    end
    return nothing
end

load_worker_credentials!(s::ServerState) =
    load_records!(s.worker_credentials[], credentials_file(s), "worker_credentials.json", WorkerCredential)
load_accounts!(s::ServerState) =
    load_records!(s.accounts[], accounts_file(s), "accounts.json", Account)
load_invites!(s::ServerState) =
    load_records!(s.invites[], invites_file(s), "invites.json", Invite)

save_worker_credentials!(s::ServerState) = lock(s.lock) do
    atomic_write_json(credentials_file(s), [Dict(c) for c in values(s.worker_credentials[])]; mode = 0o600)
end
save_accounts!(s::ServerState) = lock(s.lock) do
    atomic_write_json(accounts_file(s), [Dict(a) for a in values(s.accounts[])]; mode = 0o600)
end
save_invites!(s::ServerState) = lock(s.lock) do
    atomic_write_json(invites_file(s), [Dict(i) for i in values(s.invites[])]; mode = 0o600)
end

proxy_config(auth::LoginAuth) = auth.config
proxy_config(::OpenAuth) =
    error("this server has no login proxy in front (no proxy.json): there are no accounts to manage")

# The hash Caddy checks a worker's password against: behind the proxy only. On a
# trusted network and behind a tunnel the server checks the credential's digest
# itself; on one machine no worker needs a credential.
caddy_password_hash(auth::ProxyAuth, password::AbstractString) = caddy_hash(auth.config, password)
caddy_password_hash(::Union{NetworkAuth,TunnelAuth}, password::AbstractString) = ""
caddy_password_hash(::LocalAuth, password::AbstractString) =
    error("only this machine reaches this server (it listens on localhost), and its workers need " *
          "no credential. To add other machines, listen on the network (--host 0.0.0.0) or put " *
          "the login proxy in front (install_server.sh).")

# Authelia's files live together, beside its users database. Without mail it
# writes what it would send (the one-time code that confirms a new second factor)
# to the notifications file.
notifications_file(cfg::ProxyConfig)   = joinpath(dirname(cfg.users_file), "notifications.txt")
authelia_config_file(cfg::ProxyConfig) = joinpath(dirname(cfg.users_file), "configuration.yml")
# Authelia's log, which the debug tools read back (`bt_dev_logs source="authelia"`)
# like the server's own: journald exists on some machines and is readable by few.
authelia_log_file(cfg::ProxyConfig)    = joinpath(dirname(cfg.users_file), "authelia.log")

"""
    watch_authelia_log!(state)

Keep Authelia's log to two generations, like the server's own, for as long as
the server runs. Authelia holds the file open for appending, so the server
copies it aside and truncates it in place (`rotate_by_copy!`); Authelia goes on
writing at the new end.
"""
watch_authelia_log!(state::ServerState) = watch_authelia_log!(state.auth, state)
watch_authelia_log!(::OpenAuth, ::ServerState) = nothing
function watch_authelia_log!(auth::LoginAuth, state::ServerState; every::Real = 600.0,
                             max_bytes::Integer = BonitoWorker.LOG_MAX_BYTES)
    path = authelia_log_file(auth.config)
    return Base.errormonitor(@async while Bonito.HTTPServer.isrunning(state.srv)
        rotate_by_copy!(path, max_bytes)
        sleep(every)
    end)
end

function rotate_by_copy!(path::AbstractString, max_bytes::Integer)
    (isfile(path) && filesize(path) > max_bytes) || return false
    cp(path, path * ".1"; force = true)
    open(identity, path, "w")          # truncated in place: the writer keeps its descriptor
    return true
end

# Authelia's secrets, made once and kept in the state dir: a new session secret
# would log everyone out, a new storage key would leave its database unreadable.
authelia_secrets(state_dir::AbstractString) = (
    jwt     = bytes2hex(load_or_create_secret(state_dir, "authelia_jwt_secret")),
    session = bytes2hex(load_or_create_secret(state_dir, "authelia_session_secret")),
    storage = bytes2hex(load_or_create_secret(state_dir, "authelia_storage_key")))

smtp_settings(state_dir::AbstractString) =
    isfile(smtp_file(state_dir)) ? JSON.parsefile(smtp_file(state_dir)) : nothing

"""
    apply_proxy!(state)

Behind the proxy or a tunnel: write Authelia's users database and configuration,
and behind the proxy the Caddyfile, from the server's records. Caddy (running
with `--watch`) and Authelia (watching its users file) reread the Caddyfile and
the users database when they change; the configuration only changes with
`proxy.json`, which the installer follows with a restart. A Caddyfile Caddy
would reject is not written: it keeps serving the last good one, and the error
reaches whoever changed it. Without a login there is nothing to do.
"""
apply_proxy!(state::ServerState) = apply_proxy!(state.auth, root_state(state))
apply_proxy!(::OpenAuth, ::ServerState) = nothing

function apply_proxy!(auth::LoginAuth, root::ServerState)
    cfg = auth.config
    writer = root.proxy_writer
    # Rendered and written as one step, one writer at a time: two changes at
    # once must not leave the earlier state on disk.
    lock(writer.lock) do
        write_front!(auth, root)
        users = lock(() -> render_users_yaml(values(root.accounts[])), root.lock)
        # Authelia rereads its users database when the file changes, but a
        # change within half a second of its last reread is dropped, not
        # deferred: Authelia would keep the state before it (a disabled account
        # still able to log in) until some later change. So the file is only
        # written when it changes (a rewrite starts that half second too), and
        # never sooner than `spacing` after the last write.
        if !(isfile(cfg.users_file) && read(cfg.users_file, String) == users)
            delay = writer.users_written + writer.spacing - time()
            delay > 0 && sleep(delay)
            atomic_write(io -> write(io, users), cfg.users_file; mode = 0o600)
            writer.users_written = time()
        end
        authelia = render_authelia_config(auth, authelia_secrets(root.state_dir), smtp_settings(root.state_dir))
        atomic_write(io -> write(io, authelia), authelia_config_file(cfg); mode = 0o600)
    end
    return nothing
end

# What stands in front of the server: behind the proxy Caddy, whose Caddyfile
# carries the worker credentials; behind a tunnel nothing of ours.
function write_front!(auth::ProxyAuth, root::ServerState)
    cfg = auth.config
    caddyfile = lock(() -> render_caddyfile(auth, values(root.worker_credentials[])), root.lock)
    candidate = cfg.caddyfile * ".new"
    atomic_write(io -> write(io, caddyfile), candidate; mode = 0o600)
    try
        check_caddyfile(cfg, candidate)
    catch
        rm(candidate; force = true)
        rethrow()
    end
    mv(candidate, cfg.caddyfile; force = true)
    return nothing
end
write_front!(::TunnelAuth, ::ServerState) = nothing

# ── Worker credentials ───────────────────────────────────────────────────────

"""
    add_worker_credential!(state, owner) -> String

Issue a worker credential for `owner` ("Add worker"): checked on `/w` from now
on, by Caddy behind the proxy and by the server itself on a trusted network.
Returns `name:password`, the only time the password exists outside its hashes;
the install command carries it to the new machine.
"""
function add_worker_credential!(state::ServerState, owner::AbstractString)
    root = root_state(state)
    name = "w-" * bytes2hex(rand(Random.RandomDevice(), UInt8, 4))
    password = bytes2hex(rand(Random.RandomDevice(), UInt8, 24))
    cred = WorkerCredential(name, caddy_password_hash(root.auth, password), String(owner), now(UTC),
                            credential_digest(password))
    lock(root.lock) do
        root.worker_credentials[][name] = cred
        save_worker_credentials!(root)
    end
    apply_proxy!(root)
    safe_notify!(root.worker_credentials)
    @info "worker credential issued" name owner
    return name * ":" * password
end

"""
    revoke_worker_credential!(state, name) -> Bool

Take a worker credential back: it is refused from now on, and a worker that is
connected with it is disconnected (its reconnect meets the refusal).
"""
function revoke_worker_credential!(state::ServerState, name::AbstractString)
    root = root_state(state)
    removed = lock(root.lock) do
        c = pop!(root.worker_credentials[], String(name), nothing)
        c === nothing || save_worker_credentials!(root)
        c
    end
    removed === nothing && return false
    apply_proxy!(root)
    safe_notify!(root.worker_credentials)
    for (wid, w) in lock(() -> collect(root.workers[]), root.lock)
        w.credential == name || continue
        link = worker_link(root, wid)
        link === nothing || WorkerLink.kill!(link, "the worker's credential was revoked")
    end
    @info "worker credential revoked" name
    return true
end

# ── Accounts ─────────────────────────────────────────────────────────────────

# Change the accounts, then persist them and hand them to Authelia.
function update_accounts!(f::Function, state::ServerState)
    root = root_state(state)
    proxy_config(root.auth)
    lock(root.lock) do
        f(root.accounts[])
        save_accounts!(root)
    end
    apply_proxy!(root)
    safe_notify!(root.accounts)
    return nothing
end

function account(state::ServerState, name::AbstractString)
    a = lock(() -> get(root_state(state).accounts[], String(name), nothing), state.lock)
    a === nothing && error("there is no account '$(name)'")
    return a
end

# The server must keep an admin who can log in, and nobody locks themselves out.
function check_admin_remains(state::ServerState, name::AbstractString)
    state.user !== nothing && state.user.name == name &&
        error("you cannot do that to your own account")
    others = lock(state.lock) do
        count(a -> a.name != name && is_admin(a) && !a.disabled, values(root_state(state).accounts[]))
    end
    others == 0 && error("'$(name)' is the last admin who can log in")
    return nothing
end

"""
    Authenticator

An account's second factor, registered by the server (`register_authenticator!`):
`uri` is what an authenticator app or a password manager takes (`otpauth://…`),
`qr` the same as a QR code (PNG). Shown once, to whoever the account is for.
"""
struct Authenticator
    uri::String
    qr::Vector{UInt8}
end

"""
    register_authenticator!(state, name) -> Authenticator

Give `name` a new authenticator (a one-time-code secret), replacing any before
it. Registered with Authelia by the server, so nobody has to confirm who they are
by mail first, which is Authelia's own way of adding one. Signed in with it, a
passkey is added on Authelia's settings page without mail too
(`skip_second_factor`), and then signs in alone.
"""
function register_authenticator!(state::ServerState, name::AbstractString)
    cfg = proxy_config(state.auth)
    config = authelia_config_file(cfg)
    migrate_authelia_storage(cfg)
    authenticator = mktempdir() do dir
        png = joinpath(dir, "qr.png")
        out = read(`$(cfg.authelia_bin) storage user totp generate $(name) --force --config $(config) --path $(png)`, String)
        uri = match(r"with URI '(otpauth://[^']+)'", out)
        uri === nothing && error("`authelia storage user totp generate` printed no URI: $(out)")
        Authenticator(String(uri[1]), read(png))
    end
    @info "authenticator registered" name
    return authenticator
end

# Authelia's database at its current schema: a fresh install has none before
# Authelia first starts. Authelia calls a database that is up to date already an
# error; for us it is the common case.
function migrate_authelia_storage(cfg::ProxyConfig)
    out = IOBuffer()
    p = run(pipeline(ignorestatus(`$(cfg.authelia_bin) storage migrate up --config $(authelia_config_file(cfg))`);
                     stdout = out, stderr = out))
    text = String(take!(out))
    success(p) || occursin("schema already up to date", text) ||
        error("`authelia storage migrate up` failed: $(strip(text))")
    return nothing
end

"""
    add_account!(state, name; display_name, email, groups) -> (; password, authenticator)

A new login in `groups` ("admins" makes an admin), accepted by Authelia once it
rereads its users database (it watches the file). Returns the account's password,
generated by Authelia, and its authenticator, for its owner; they exist nowhere
else.
"""
function add_account!(state::ServerState, name::AbstractString;
                      display_name::AbstractString = name, email::AbstractString = "",
                      groups::Vector{String} = String[])
    cfg = proxy_config(state.auth)
    valid_name(name) ||
        error("an account name is letters, digits, '.', '_' and '-' (got '$(name)')")
    haskey(root_state(state).accounts[], name) && error("there is an account '$(name)' already")
    pw = authelia_random_password(cfg)
    acct = Account(String(name), isempty(display_name) ? String(name) : String(display_name),
                   String(email), groups, false, pw.hash)
    update_accounts!(state) do accounts
        # Checked again under the lock: two requests for one name, one account.
        haskey(accounts, acct.name) && error("there is an account '$(acct.name)' already")
        accounts[acct.name] = acct
    end
    @info "account added" name groups
    # Only once the account is ours: registering replaces what is there, and a
    # name someone else holds must keep theirs. An account without one does not
    # stay: nobody could log in with it.
    authenticator = try
        register_authenticator!(state, acct.name)
    catch
        update_accounts!(accounts -> delete!(accounts, acct.name), state)
        rethrow()
    end
    return (password = pw.password, authenticator)
end

"How someone adds an authenticator: once, from what the server shows them."
const AUTHENTICATOR_HELP = "Scan it with an authenticator app or your password manager, or paste the link there."

qr_data_uri(a::Authenticator) = "data:image/png;base64," * Base64.base64encode(a.qr)

"An authenticator on the dashboard, for whoever it is shown to once."
authenticator_dom(a::Authenticator) =
    DOM.div(DOM.img(src = qr_data_uri(a), alt = "authenticator QR code", class = "bt-admin-qr"),
            DOM.div(AUTHENTICATOR_HELP; class = "bt-admin-muted"),
            DOM.code(a.uri; class = "bt-admin-uri"))

"A new random password for `name`, generated by Authelia; returned once."
function reset_account_password!(state::ServerState, name::AbstractString)
    a = account(state, name)
    pw = authelia_random_password(proxy_config(state.auth))
    update_accounts!(_ -> (a.password_hash = pw.hash), state)
    return pw.password
end

"""
    set_account_disabled!(state, name, disabled)

Authelia refuses a disabled account's next request; its open tabs are closed here,
since an open websocket is never re-checked.
"""
function set_account_disabled!(state::ServerState, name::AbstractString, disabled::Bool)
    a = account(state, name)
    disabled && is_admin(a) && check_admin_remains(state, name)
    update_accounts!(_ -> (a.disabled = disabled), state)
    disabled && close_user_sessions!(state, name)
    return nothing
end

"""
    set_account_groups!(state, name, groups)

Put `name` in exactly `groups`. "admins" makes an admin; any other group is one
workers can be shared with (`share_worker!`).
"""
function set_account_groups!(state::ServerState, name::AbstractString, groups::Vector{String})
    a = account(state, name)
    is_admin(a) && !("admins" in groups) && check_admin_remains(state, name)
    update_accounts!(_ -> (a.groups = groups), state)
    # The groups arrive with the next request through Authelia: reload the tabs.
    close_user_sessions!(state, name)
    return nothing
end

set_account_admin!(state::ServerState, name::AbstractString, admin::Bool) =
    set_account_groups!(state, name, admin ? union(account(state, name).groups, ["admins"]) :
                                             setdiff(account(state, name).groups, ["admins"]))

function remove_account!(state::ServerState, name::AbstractString)
    a = account(state, name)
    is_admin(a) && check_admin_remains(state, name)
    state.user !== nothing && state.user.name == name && error("you cannot remove your own account")
    update_accounts!(accounts -> delete!(accounts, a.name), state)
    close_user_sessions!(state, name)
    return nothing
end

"Every group some account is in, sorted."
all_groups(state::ServerState) =
    sort!(unique!(String[g for a in values(root_state(state).accounts[]) for g in a.groups]))

# ── Invites ──────────────────────────────────────────────────────────────────

"""
    create_invite!(state, groups; valid_for = Day(7)) -> String

A link that lets one person create their own account in `groups`, valid for
`valid_for`. The link is returned here only; the server keeps its token's hash.
"""
function create_invite!(state::ServerState, groups::Vector{String}; valid_for::Period = Day(7))
    root = root_state(state)
    proxy_config(root.auth)
    token = bytes2hex(rand(Random.RandomDevice(), UInt8, 32))
    t = now(UTC)
    invite = Invite(invite_id(token), groups, acting_owner(state), t, t + valid_for)
    lock(root.lock) do
        filter!(((_, i),) -> i.expires > t, root.invites[])   # expired ones go with it
        root.invites[][invite.id] = invite
        save_invites!(root)
    end
    safe_notify!(root.invites)
    @info "invite created" groups by = invite.created_by expires = invite.expires
    return install_base_url(root) * "/invite/" * token
end

function revoke_invite!(state::ServerState, id::AbstractString)
    root = root_state(state)
    removed = lock(root.lock) do
        i = pop!(root.invites[], String(id), nothing)
        i === nothing || save_invites!(root)
        i
    end
    removed === nothing && return false
    safe_notify!(root.invites)
    return true
end

"The invite a link carries, while it is good for an account; `nothing` otherwise."
function open_invite(state::ServerState, token::AbstractString)
    i = lock(() -> get(root_state(state).invites[], invite_id(token), nothing), state.lock)
    return (i === nothing || i.expires <= now(UTC)) ? nothing : i
end

"""
    redeem_invite!(state, token, name; display_name, email) -> (; password, authenticator)

Create the account an invite link offers, and use the link up. Returns the new
account's password and authenticator, which its owner sees once.
"""
function redeem_invite!(state::ServerState, token::AbstractString, name::AbstractString;
                        display_name::AbstractString = name, email::AbstractString = "")
    root = root_state(state)
    id = invite_id(token)
    # Taken out first, so two submissions of one link cannot make two accounts.
    invite = lock(() -> pop!(root.invites[], id, nothing), root.lock)
    invite === nothing && error("this invite link was used already or revoked")
    if invite.expires <= now(UTC)
        save_invites!(root)
        safe_notify!(root.invites)
        error("this invite link has expired")
    end
    login = try
        add_account!(root, name; display_name, email, groups = invite.groups)
    catch e
        # A name that is taken or not allowed: the link stays good for another try.
        lock(() -> (root.invites[][id] = invite), root.lock)
        rethrow()
    end
    save_invites!(root)
    safe_notify!(root.invites)
    @info "invite used" name invited_by = invite.created_by
    return login
end

"""
    redeem_setup!(state, token) -> (; password, authenticator)

Use up a setup link (an invite for an existing account): the account gets a new
password and authenticator, returned for its owner to see once.
"""
function redeem_setup!(state::ServerState, token::AbstractString)
    root = root_state(state)
    invite = lock(() -> pop!(root.invites[], invite_id(token), nothing), root.lock)
    invite === nothing && error("this setup link was used already or revoked")
    save_invites!(root)
    safe_notify!(root.invites)
    invite.expires <= now(UTC) && error("this setup link has expired")
    isempty(invite.account) && error("this is an invite for a new account, not a setup link")
    password = reset_account_password!(root, invite.account)
    @info "setup link used" name = invite.account
    return (password = password, authenticator = register_authenticator!(root, invite.account))
end

# The installer hands the first admin a setup link rather than codes: it writes
# the token's hash here, and the server files it with the invites when it starts.
setup_link_file(state::ServerState) = joinpath(state.state_dir, "setup_link.json")

function import_setup_link!(state::ServerState)
    f = setup_link_file(state)
    isfile(f) || return nothing
    d = JSON.parsefile(f)
    invite = Invite(String(d["token_sha256"]), String[], "installer", now(UTC),
                    DateTime(String(d["expires"])), String(d["account"]))
    lock(state.lock) do
        state.invites[][invite.id] = invite
        save_invites!(state)
    end
    rm(f)
    safe_notify!(state.invites)
    @info "setup link from the installer filed" account = invite.account expires = invite.expires
    return nothing
end

# /invite/<token>: open to anyone (the token is the proof), so it is plain HTML
# with a form, no dashboard session.
const INVITE_ROUTE_RE = r"^/invite/([0-9a-f]{64})/?(?:$|\?)"

function add_invite_routes!(srv::Bonito.Server, state::ServerState)
    Bonito.route!(srv, INVITE_ROUTE_RE => function(context)
        invite_response(state.auth, state, context.request, String(context.match.captures[1]))
    end)
end

invite_response(::OpenAuth, state::ServerState, request, token::AbstractString) =
    invite_page(404, "Not found", "<p>This server has no accounts to invite anyone to.</p>")

function invite_response(auth::LoginAuth, state::ServerState, request, token::AbstractString)
    invite = open_invite(state, token)
    invite === nothing && return invite_page(404, "This invite is not valid",
        "<p>The link was used already, revoked, or has expired. Ask for a new one.</p>")
    isempty(invite.account) || return setup_response(auth, state, request, token, invite.account)
    request.method == "POST" ||
        return invite_page(200, "Create your account", invite_form(Dict{String,String}(), ""))
    form = form_fields(String(request.body))
    name = strip(get(form, "name", ""))
    display_name = strip(get(form, "display_name", ""))
    login = try
        redeem_invite!(state, token, name; display_name = isempty(display_name) ? name : display_name,
                       email = strip(get(form, "email", "")))
    catch e
        (e isa ErrorException || e isa ProcessFailedException || e isa Base.IOError) || rethrow()
        return invite_page(400, "Create your account",
                           invite_form(form, first(split(sprint(showerror, e), '\n'))))
    end
    return account_ready_page(auth, name, login)
end

# A setup link: the account exists; opening it (and confirming) gives it a new
# password and authenticator, and the page that makes a passkey.
function setup_response(auth::LoginAuth, state::ServerState, request, token::AbstractString, name::AbstractString)
    request.method == "POST" || return invite_page(200, "Set up your login", """
        <p>This sets up how <b>$(esc_html(name))</b> signs in: a passkey, or a password and an authenticator.
        The link works once.</p>
        <form method="post"><button type="submit">Set up my login</button></form>""")
    login = try
        redeem_setup!(state, token)
    catch e
        (e isa ErrorException || e isa ProcessFailedException || e isa Base.IOError) || rethrow()
        return invite_page(400, "Set up your login", "<p class=\"err\">$(esc_html(first(split(sprint(showerror, e), '\n'))))</p>")
    end
    return account_ready_page(auth, name, login)
end

function invite_form(form::AbstractDict, error_message::AbstractString)
    field(key, label, type = "text") = """
        <label>$(label)<input type="$(type)" name="$(key)" value="$(esc_html(get(form, key, "")))"></label>"""
    err = isempty(error_message) ? "" : "<p class=\"err\">$(esc_html(error_message))</p>"
    return """
        $(err)
        <form method="post">
        $(field("name", "Account name (letters, digits, '.', '_', '-')"))
        $(field("display_name", "Full name"))
        $(field("email", "Email", "email"))
        <button type="submit">Create account</button>
        </form>"""
end

function invite_page(status::Int, title::AbstractString, body::AbstractString)
    html = """<!doctype html><html><head><meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>$(esc_html(title))</title><style>
        body { font-family: system-ui, sans-serif; background: #f5f5f4; color: #1c1917; }
        main { max-width: 30rem; margin: 4rem auto; padding: 2rem; background: #fff; border-radius: 10px; }
        label { display: block; margin: 0.8rem 0; font-size: 0.9rem; }
        input { display: block; width: 100%; box-sizing: border-box; margin-top: 0.3rem; padding: 0.5rem;
                border: 1px solid #d6d3d1; border-radius: 6px; font-size: 1rem; }
        button { margin-top: 1rem; padding: 0.6rem 1.2rem; border: 0; border-radius: 6px;
                 background: #1c1917; color: #fff; font-size: 1rem; cursor: pointer; }
        .err { color: #b91c1c; }
        .pw { font-size: 1.2rem; padding: 0.3rem 0.5rem; background: #f5f5f4; user-select: all; }
        .qr { width: 12rem; image-rendering: pixelated; }
        .uri { font-size: 0.8rem; word-break: break-all; user-select: all; }
        .status { color: #57534e; min-height: 1.2em; }
        details { margin-top: 1.5rem; } summary { cursor: pointer; color: #57534e; }
        </style></head><body><main><h1>$(esc_html(title))</h1>$(body)</main></body></html>"""
    # The token is in the URL: no Referer carries it anywhere, nothing caches it.
    return HTTP.Response(status, ["Content-Type" => "text/html; charset=utf-8",
                                  "Cache-Control" => "no-store", "Referrer-Policy" => "no-referrer"];
                         body = html)
end

# An `application/x-www-form-urlencoded` body: `+` is a space there.
function form_fields(body::AbstractString)
    fields = Dict{String,String}()
    for pair in split(body, '&'; keepempty = false)
        k, v = occursin('=', pair) ? split(pair, '='; limit = 2) : (pair, "")
        fields[HTTP.unescapeuri(replace(k, '+' => ' '))] = HTTP.unescapeuri(replace(v, '+' => ' '))
    end
    return fields
end

# ── Who sees what ────────────────────────────────────────────────────────────

"""
    visible(state, chat_or_worker) -> Bool

May the person `state` serves see this chat or worker? Admins see everything,
members what they own, and the workers shared with a group they are in. The
server's own view (no user) sees everything.
"""
visible(state::ServerState, x) = visible(state.user, x)
visible(::Nothing, x) = true
visible(user::User, p::ProjectInfo) = is_admin(user) || p.owner == user.name
visible(user::User, w::WorkerInfo) =
    is_admin(user) || w.owner == user.name || !isdisjoint(w.shared_with, user.groups)

"Does `state` serve an admin? The server's own view (no user) acts as one."
is_admin(state::ServerState) = state.user === nothing || is_admin(state.user)

"May the person `state` serves rename, update, share or remove this worker?"
can_manage(state::ServerState, w::WorkerInfo) = can_manage(state.user, w)
can_manage(::Nothing, w::WorkerInfo) = true
can_manage(user::User, w::WorkerInfo) = is_admin(user) || w.owner == user.name

"""
    share_worker!(state, worker_id, groups)

Let the members of `groups` see the worker and start chats on it. Sharing a
worker shares its machine: their agents run there as the worker's user.
"""
function share_worker!(state::ServerState, worker_id::AbstractString, groups::Vector{String})
    root = root_state(state)
    lock(root.lock) do
        w = get(root.workers[], String(worker_id), nothing)
        w === nothing && error("there is no worker '$(worker_id)'")
        w.shared_with = groups
        save_workers!(root)
    end
    notify_workers!(root)
    @info "worker shared" worker_id groups
    return nothing
end

# Live browser sessions by user, so disabling an account can end them.
function register_user_session!(state::ServerState, session::Bonito.Session, user::User)
    root = root_state(state)
    lock(root.lock) do
        push!(get!(Vector{Bonito.Session}, root.user_sessions, user.name), session)
    end
    on(session.on_close) do closed
        closed || return
        lock(root.lock) do
            list = get(root.user_sessions, user.name, nothing)
            list === nothing || filter!(s -> s !== session, list)
        end
    end
    return nothing
end

function close_user_sessions!(state::ServerState, name::AbstractString)
    root = root_state(state)
    sessions = lock(() -> pop!(root.user_sessions, String(name), Bonito.Session[]), root.lock)
    foreach(close, sessions)
    return length(sessions)
end

# ── Agent adapters ───────────────────────────────────────────────────────────

"""
    set_harness_spec!(state, spec)

Change which agent adapters workers keep installed, and at which versions:
persisted, and sent to every connected worker right away (a worker that is
offline gets it with its next hello acknowledgement).
"""
function set_harness_spec!(state::ServerState, spec::Dict{String,Any})
    root = root_state(state)
    root.harness_spec[] = spec
    save_settings!(root)
    links = lock(() -> collect(root.worker_links), root.lock)
    for (wid, link) in links
        WorkerLink.state(link) === :connected || continue
        try
            send_command(root, wid, Dict("type" => "harness_spec", "spec" => spec))
        catch e
            # The worker dropped between the check and the send; its next hello
            # acknowledgement carries the spec.
            (e isa WebSockets.WebSocketError || e isa WorkerLink.LinkDead) || rethrow()
        end
    end
    return nothing
end

# ── Dashboard controls ───────────────────────────────────────────────────────

const AdminStyles = Bonito.Styles(
    CSS(".bt-admin-table",
        "width" => "100%", "border-collapse" => "collapse", "font-size" => "13px"),
    CSS(".bt-admin-table th, .bt-admin-table td",
        "text-align" => "left", "padding" => "6px 8px",
        "border-bottom" => "1px solid var(--bt-border)"),
    CSS(".bt-admin-table th",
        "color" => "var(--bt-text-faint)", "font-weight" => "600", "font-size" => "11px",
        "text-transform" => "uppercase", "letter-spacing" => "0.04em"),
    CSS(".bt-admin-form",
        "display" => "flex", "gap" => "8px", "flex-wrap" => "wrap", "align-items" => "center",
        "margin-top" => "10px"),
    CSS(".bt-admin-form input[type=text], .bt-admin-table input[type=text]",
        "padding" => "5px 8px", "border" => "1px solid var(--bt-border)",
        "border-radius" => "var(--bt-radius-sm)", "background" => "var(--bt-surface)",
        "color" => "var(--bt-text)", "font-size" => "13px"),
    CSS(".bt-admin-status",
        "font-size" => "12px", "color" => "var(--bt-text-muted)", "margin-top" => "8px"),
    CSS(".bt-admin-secret",
        "margin-top" => "10px", "user-select" => "all"),
    # Commands with their own Copy buttons: a click must not select the block.
    CSS(".bt-install-issued", "margin-top" => "10px"),
    CSS(".bt-install-again", "margin-top" => "14px"),
    CSS(".bt-admin-muted",
        "color" => "var(--bt-text-muted)"),
    CSS(".bt-admin-qr",
        "width" => "180px", "image-rendering" => "pixelated", "display" => "block", "margin" => "6px 0"),
    CSS(".bt-admin-uri",
        "font-size" => "11px", "word-break" => "break-all", "user-select" => "all"),
    CSS(".bt-accounts-table td", "vertical-align" => "middle"),
    # The group picker: a list that opens below its button, left-aligned (it
    # sits at the start of its cell), checkboxes in front of the names.
    CSS(".bt-group-pick .bt-menu-list",
        "left" => "0", "right" => "auto", "max-height" => "300px", "overflow-y" => "auto"),
    CSS(".bt-menu-item.bt-group-item",
        "display" => "flex", "align-items" => "center", "gap" => "8px"),
    CSS(".bt-group-item input", "margin" => "0"),
    CSS(".bt-group-trigger",
        "display" => "inline-flex", "align-items" => "center", "gap" => "6px", "max-width" => "260px"),
    CSS(".bt-group-label",
        "overflow" => "hidden", "text-overflow" => "ellipsis", "white-space" => "nowrap"),
    CSS(".bt-group-new",
        "display" => "flex", "gap" => "6px", "padding" => "6px 6px 2px",
        "border-top" => "1px solid var(--bt-border)", "margin-top" => "4px"),
    CSS(".bt-group-new input",
        "flex" => "1 1 auto", "min-width" => "0", "padding" => "4px 8px",
        "border" => "1px solid var(--bt-border)", "border-radius" => "var(--bt-radius-sm)",
        "background" => "var(--bt-surface)", "color" => "var(--bt-text)", "font-size" => "13px"),
    CSS(".bt-worker-sharing", "margin-top" => "0"),
    # A status inside a row of controls sits on the row's line, not below it.
    CSS(".bt-admin-form .bt-admin-status", "margin-top" => "0"),
    # The groups field takes its column's width, not its default 20 characters:
    # on a phone those pushed Role and ⋯ out of the card.
    CSS(".bt-accounts-table input[type=text]",
        "width" => "100%", "min-width" => "4em", "box-sizing" => "border-box"),
    # A checkbox in a `.bt-form`'s value column: box and text on one line.
    CSS(".bt-form .bt-form-check",
        "display" => "flex", "align-items" => "center", "gap" => "8px",
        "color" => "var(--bt-text)"),
    CSS(".bt-form .bt-form-check input", "width" => "auto", "margin" => "0"),
    CSS(".bt-form .bt-admin-status", "grid-column" => "1 / -1", "margin-top" => "0"),
    # The group picker inside a form: its button keeps its own size, and the
    # form's input styling stays off its checkboxes.
    CSS(".bt-form .bt-group-pick", "justify-self" => "start"),
    CSS(".bt-form .bt-group-item input", "width" => "auto", "padding" => "0"),
    CSS(".bt-form .bt-group-new input", "padding" => "4px 8px", "font-size" => "13px"),
    CSS(".bt-account-name", "font-weight" => "600"),
    CSS(".bt-account-detail", "font-size" => "12px", "overflow-wrap" => "anywhere"),
    CSS("@media (max-width: 560px)",
        CSS(".bt-admin-table th, .bt-admin-table td", "padding" => "6px 4px")),
    CSS(".bt-account-off td:not(.bt-admin-menu-cell)", "opacity" => "0.55"),
    CSS(".bt-account-disabled", "margin-left" => "6px"),
    CSS(".bt-admin-menu-cell", "width" => "1%", "text-align" => "right"),
    CSS(".bt-admin-pre",
        "white-space" => "pre-wrap", "font-size" => "12px", "max-height" => "240px",
        "overflow" => "auto", "margin-top" => "8px"),
)

# An action run from a button: `f()` returns a status line, or a failure the
# person should read (a name taken, the last admin, Caddy or Authelia refusing)
# is shown instead.
function admin_action!(status::Observable{String}, f::Function)
    msg = try
        f()
    catch e
        (e isa ErrorException || e isa ProcessFailedException || e isa Base.IOError ||
         e isa HTTP.Exceptions.HTTPError) || rethrow()
        @warn "account action failed" exception = (e, catch_backtrace())
        first(split(sprint(showerror, e), '\n'))
    end
    safe_set!(status, String(msg))
    return nothing
end

# A status or a shown-once secret under a card's controls. Out of the layout
# while it is empty: an empty line still took a flex gap and its own margin.
admin_line(obs::Observable, class::AbstractString) =
    DOM.div(obs; class = map(v -> v == "" ? "$(class) bt-hidden" : class, obs))

"""
    pickable_groups(state) -> Vector{String}

The groups this viewer can pick from: an admin every group some account is in, a
member their own. Never `admins`, which is a role (an account's ⋯ menu), not a
group to share with.
"""
function pickable_groups(state::ServerState)
    gs = is_admin(state) ?
        reduce(union, (a.groups for a in values(state.accounts[])); init = String[]) :
        copy(state.user.groups)
    return sort!(filter!(!=("admins"), gs))
end

# The picker's popover. Opening remembers the ticked set; closing (a click
# outside, or the button again) hands the new set to the caller's `commit`, once
# and only if it changed: saving on every tick re-rendered the accounts table
# and closed the list under the pointer.
const GROUP_PICK_JS = """
    event.stopPropagation();
    const m = event.currentTarget.closest('.bt-group-pick');
    if (m.__close) { m.__close(); return; }
    const picked = () => [...m.querySelectorAll('.bt-group-item input:checked')].map(i => i.value);
    const before = JSON.stringify(picked());
    m.__show = () => {
        const p = picked();
        m.querySelector('.bt-group-label').textContent = p.length ? p.join(', ') : m.dataset.empty;
    };
    m.classList.add('bt-menu-open');
    const outside = ev => { if (!m.contains(ev.target)) m.__close(); };
    m.__close = () => {
        m.classList.remove('bt-menu-open');
        document.removeEventListener('click', outside, true);
        m.__close = null;
        const now = picked();
        if (JSON.stringify(now) !== before) commit(now);
    };
    document.addEventListener('click', outside, true);"""

"""
    group_picker(groups, current, commit; empty = "none", allow_new = false) -> Node

Groups are picked, never typed: a button naming the chosen ones, and a list of
checkboxes over `groups`. `commit` is a JS function called with the chosen names
when the list closes. `allow_new` adds a field for a group nobody is in yet.
"""
function group_picker(groups::Vector{String}, current::Vector{String}, commit::Bonito.JSCode;
                      empty::AbstractString = "none", allow_new::Bool = false)
    item(g) = DOM.label(g in current ? DOM.input(type = "checkbox", value = g, checked = true) :
                                       DOM.input(type = "checkbox", value = g),
                        g; class = "bt-menu-item bt-group-item")
    add = js"""event => {
        const m = event.currentTarget.closest('.bt-group-pick');
        const field = m.querySelector('.bt-group-new-name');
        const name = field.value.trim();
        if (!name) return;
        let box = [...m.querySelectorAll('.bt-group-item input')].find(i => i.value === name);
        if (!box) {
            const row = document.createElement('label');
            row.className = 'bt-menu-item bt-group-item';
            box = document.createElement('input');
            box.type = 'checkbox'; box.value = name;
            row.append(box, name);
            m.querySelector('.bt-group-items').append(row);
        }
        box.checked = true;
        field.value = '';
        m.__show && m.__show();
    }"""
    new_row = !allow_new ? nothing : DOM.div(
        DOM.input(type = "text", placeholder = "new group", class = "bt-group-new-name",
                  onkeydown = js"""event => { if (event.key === 'Enter') {
                      event.preventDefault(); event.target.nextElementSibling.click(); } }"""),
        DOM.button("Add"; class = "bt-btn bt-btn-secondary bt-btn-sm bt-group-add", onclick = add);
        class = "bt-group-new")
    all = sort!(union(groups, current))
    return DOM.div(
        DOM.button(DOM.span(isempty(current) ? empty : join(current, ", "); class = "bt-group-label"),
                   DOM.span("▾"; class = "bt-msearch-caret");
                   class = "bt-btn bt-btn-secondary bt-btn-sm bt-group-trigger",
                   onclick = js"""event => {
                       const commit = $(commit);
                       $(Bonito.JSString(GROUP_PICK_JS))
                   }"""),
        DOM.div(
            DOM.div((item(g) for g in all)...; class = "bt-group-items"),
            isempty(all) && !allow_new ? DOM.div("No groups yet: an admin puts accounts in groups.";
                                                  class = "bt-menu-title") : nothing,
            new_row;
            class = "bt-menu-list",
            # `__show` keeps the button's label with the ticks.
            onchange = js"event => { const m = event.currentTarget.closest('.bt-group-pick'); m.__show && m.__show(); }");
        class = "bt-menu bt-group-pick", dataEmpty = empty)
end

text_input(obs::Observable{String}, placeholder::AbstractString) =
    DOM.input(type = "text", placeholder = placeholder, value = obs,
              oninput = js"event => $(obs).notify(event.target.value)")

"""
    worker_install_block(auth, session, state)

"Add worker" where other machines connect (behind the proxy, or on a trusted
network): an admin issues a credential and gets the install command that carries
it (shown once); the credentials issued so far can be revoked, and the command
without one reinstalls a machine that has its credential. A member is told to
ask an admin. (One machine's server has no credentials: dashboard.jl.)
"""
function worker_install_block(::Union{LoginAuth,NetworkAuth}, session::Bonito.Session, state::ServerState)
    summary = DOM.summary(DOM.span("Add a worker"; class = "bt-discover-title");
                          class = "bt-discover-header")
    if !is_admin(state)
        return DOM.details(summary,
            DOM.div("An admin adds workers: each machine gets its own credential.";
                    class = "bt-install-block bt-admin-muted");
            class = "bt-card bt-install-details")
    end
    base = install_base_url(state)
    issued = Observable{Any}(DOM.div())
    status = Observable("")
    add = Observable(false)
    revoke = Observable("")
    on(session, add) do _
        admin_action!(status, () -> begin
            cred = add_worker_credential!(state, state.user.name)
            unix = "curl -fsSL $(base)/install.sh | sh -s $(cred)"
            win  = "& ([scriptblock]::Create((irm $(base)/install.ps1))) $(cred)"
            issued[] = DOM.div(
                DOM.div("Run this on the new machine. It carries the worker's credential, " *
                        "shown only now; revoking it below disconnects that worker.";
                        class = "bt-admin-muted"),
                install_command_row("Linux / macOS", unix),
                install_command_row("Windows (PowerShell)", win);
                class = "bt-install-issued")
            "credential $(first(split(cred, ':'))) issued"
        end)
    end
    on(session, revoke) do name
        isempty(name) && return
        admin_action!(status, () ->
            revoke_worker_credential!(state, name) ? "revoked $(name)" : "$(name) was already gone")
    end
    creds = map(session, state.worker_credentials, state.workers) do creds, workers
        isempty(creds) && return DOM.div("No worker credentials issued yet."; class = "bt-admin-muted")
        rows = map(sort!(collect(values(creds)); by = c -> c.created)) do c
            used = [w.name for w in values(workers) if w.credential == c.name]
            DOM.tr(DOM.td(DOM.code(c.name)), DOM.td(isempty(used) ? "not connected yet" : join(used, ", ")),
                   DOM.td(c.owner), DOM.td(Dates.format(c.created, "yyyy-mm-dd")),
                   DOM.td(DOM.button("Revoke"; class = "bt-btn bt-btn-sm bt-btn-secondary",
                                     onclick = js"event => $(revoke).notify($(c.name))")))
        end
        DOM.table(DOM.tr(DOM.th("Credential"), DOM.th("Worker"), DOM.th("Issued by"),
                         DOM.th("Issued"), DOM.th("")), rows...; class = "bt-admin-table")
    end
    body = DOM.div(
        AdminStyles,
        DOM.button("Add worker"; class = "bt-btn bt-btn-sm",
                   onclick = js"event => $(add).notify(true)"),
        issued,
        admin_line(status, "bt-admin-status"),
        creds,
        DOM.div("To update or reinstall a machine that is a worker already, run the command " *
                "without a credential: it keeps the one it has.";
                class = "bt-admin-muted bt-install-again"),
        install_command_row("Linux / macOS", "curl -fsSL $(base)/install.sh | sh"),
        install_command_row("Windows (PowerShell)", "irm $(base)/install.ps1 | iex");
        class = "bt-install-block")
    # `open` is a boolean attribute: present means open, whatever its value.
    return isempty(state.workers[]) ?
        DOM.details(summary, body; class = "bt-card bt-install-details", open = true) :
        DOM.details(summary, body; class = "bt-card bt-install-details")
end

"""
    account_sections(session, state)

The Settings page's account sections: everyone's own account behind the proxy, and
for admins the accounts, the invites and the agent adapter versions workers keep
installed.
"""
function account_sections(session::Bonito.Session, state::ServerState)
    state.user === nothing && return DOM.div()
    admin = is_admin(state)
    return DOM.div(AdminStyles,
                   own_account_section(state.auth, session, state),
                   admin ? accounts_section(state.auth, session, state) : DOM.div(),
                   admin ? invites_section(state.auth, session, state) : DOM.div(),
                   admin ? adapters_section(session, state) : DOM.div())
end

own_account_section(::OpenAuth, session::Bonito.Session, state::ServerState) = DOM.div()

function own_account_section(auth::LoginAuth, session::Bonito.Session, state::ServerState)
    user = state.user
    status = Observable("")
    secret = Observable{Any}("")
    renew = Observable(false)
    reauth = Observable(false)
    on(session, renew) do _
        admin_action!(status, () -> begin
            secret[] = "Your new password, shown only now: " * reset_account_password!(state, user.name)
            "new password set"
        end)
    end
    on(session, reauth) do _
        admin_action!(status, () -> begin
            secret[] = authenticator_dom(register_authenticator!(state, user.name))
            "new authenticator set; the old one no longer works"
        end)
    end
    groups = isempty(user.groups) ? "no groups" : "groups: " * join(user.groups, ", ")
    logout = portal_url(auth) * "/logout?rd=" * HTTP.escapeuri(dashboard_url(auth))
    # Passkeys first: they are how people sign in. The password and authenticator
    # are what is left for whoever cannot use one.
    return DOM.div(
        DOM.div(DOM.h2("Your account"); class = "bt-section"),
        DOM.div(
            PasskeyStyles,
            DOM.div(DOM.span("Signed in as $(user.display_name) ($(user.name)); $(groups)."),
                    DOM.a("Log out"; href = logout, class = "bt-btn bt-btn-sm bt-btn-secondary");
                    class = "bt-account-head"),
            passkeys_block(auth, session),
            DOM.div(
                DOM.span("Password and authenticator"; class = "bt-account-sub"),
                DOM.button("New password"; class = "bt-btn bt-btn-sm bt-btn-secondary",
                           onclick = js"""event => {
                               if (confirm("Replace your password with a new, generated one?"))
                                   $(renew).notify(true);
                           }"""),
                DOM.button("New authenticator"; class = "bt-btn bt-btn-sm bt-btn-secondary",
                           onclick = js"""event => {
                               if (confirm("Replace your authenticator? The codes of the old one stop working."))
                                   $(reauth).notify(true);
                           }""");
                class = "bt-admin-form bt-account-fallback"),
            admin_line(secret, "bt-admin-secret"),
            admin_line(status, "bt-admin-status");
            class = "bt-card"))
end

accounts_section(::OpenAuth, session::Bonito.Session, state::ServerState) = DOM.div()

function accounts_section(auth::LoginAuth, session::Bonito.Session, state::ServerState)
    status = Observable("")
    secret = Observable{Any}("")
    # [verb, account, ""] from a row's ⋯ menu, ["groups", account, groups] from its field.
    action = Observable{Any}(nothing)
    shown(name, pw) = "Password for $(name), shown only now: $(pw)"
    on(session, action) do a
        a isa AbstractVector && length(a) == 3 || return
        verb, name, arg = String(a[1]), String(a[2]), String(a[3])
        admin_action!(status, () -> begin
            if verb == "password"
                secret[] = shown(name, reset_account_password!(state, name))
                "new password for $(name)"
            elseif verb == "authenticator"
                secret[] = DOM.div("Authenticator for $(name), shown only now:",
                                   authenticator_dom(register_authenticator!(state, name)))
                "new authenticator for $(name); the old one no longer works"
            elseif verb == "groups"
                set_account_groups!(state, name, parse_groups(arg)); "groups of $(name) saved"
            elseif verb == "disable"
                set_account_disabled!(state, name, true); "$(name) disabled; their open tabs were closed"
            elseif verb == "enable"
                set_account_disabled!(state, name, false); "$(name) enabled"
            elseif verb == "admin"
                set_account_admin!(state, name, true); "$(name) is an admin"
            elseif verb == "member"
                set_account_admin!(state, name, false); "$(name) is a member"
            elseif verb == "remove"
                remove_account!(state, name); "$(name) removed"
            else
                error("unknown account action '$(verb)'")
            end
        end)
    end

    # ── Add account: a form over the page ────────────────────────────────────
    adding = Observable(false)
    add = Observable(false)
    add_status = Observable("")
    new_name = Observable("")
    new_display = Observable("")
    new_email = Observable("")
    new_groups = Observable("")
    new_admin = Observable(false)
    on(session, adding) do open
        open && (add_status[] = "")
    end
    on(session, add) do _
        admin_action!(add_status, () -> begin
            groups = parse_groups(new_groups[])
            new_admin[] && union!(groups, ["admins"])
            login = add_account!(state, new_name[]; display_name = new_display[],
                                 email = new_email[], groups)
            # Shown under the table, where the form was opened from.
            secret[] = DOM.div(DOM.div(shown(new_name[], login.password)), authenticator_dom(login.authenticator))
            added = new_name[]
            new_name[] = ""; new_display[] = ""; new_email[] = ""; new_groups[] = ""; new_admin[] = false
            adding[] = false
            msg = "account $(added) added"
            safe_set!(status, msg)
            msg
        end)
    end
    add_form = modal(session, adding, "Add account") do
        field(label, obs, placeholder) = (DOM.label(label), text_input(obs, placeholder))
        DOM.div(
            field("Account", new_name, "login name, e.g. dave")...,
            field("Full name", new_display, "Dave Doe")...,
            field("Email", new_email, "optional")...,
            DOM.label("Groups"),
            group_picker(pickable_groups(state),
                         String[strip(g) for g in split(new_groups[], ',') if !isempty(strip(g))],
                         js"list => $(new_groups).notify(list.join(', '))"; allow_new = true),
            DOM.label("Admin"),
            DOM.label(DOM.input(type = "checkbox", checked = new_admin,
                                onchange = js"event => $(new_admin).notify(event.target.checked)"),
                      "may manage accounts, workers and settings"; class = "bt-form-check"),
            DOM.div("The password and authenticator are shown once, after adding.";
                    class = "bt-form-note"),
            admin_line(add_status, "bt-admin-status"),
            DOM.div(DOM.button("Cancel"; class = "bt-btn bt-btn-secondary",
                               onclick = js"event => $(adding).notify(false)"),
                    DOM.button("Add account"; class = "bt-btn bt-add-account-submit",
                               onclick = js"event => $(add).notify(true)");
                    class = "bt-form-actions");
            class = "bt-form")
    end

    # ── The table: who, their groups, their role; everything else in ⋯ ──────
    item(label, verb, name; danger = false, ask = "") = DOM.button(label;
        class = danger ? "bt-menu-item bt-menu-danger" : "bt-menu-item",
        onclick = js"""event => {
            $(Bonito.JSString(MENU_CLOSE_JS))
            const ask = $(ask);
            if (!ask || confirm(ask)) $(action).notify([$(verb), $(name), '']);
        }""")
    table = map(session, state.accounts) do accounts
        groups = pickable_groups(state)
        rows = map(sort!(collect(values(accounts)); by = a -> a.name)) do a
            admin = is_admin(a)
            DOM.tr(
                DOM.td(DOM.div(a.name; class = "bt-account-name"),
                       DOM.div(isempty(a.email) ? a.display_name : "$(a.display_name) · $(a.email)";
                               class = "bt-admin-muted bt-account-detail")),
                # Workers are shared with groups. `admins` is the role, kept as it is.
                DOM.td(group_picker(groups, filter(!=("admins"), a.groups),
                           js"""list => $(action).notify(['groups', $(a.name),
                                    list.concat($(admin) ? ['admins'] : []).join(', ')])""";
                           allow_new = true)),
                DOM.td(admin ? "admin" : "member",
                       a.disabled ? DOM.span("disabled"; class = "bt-pill bt-pill-warn bt-account-disabled") : nothing),
                DOM.td(action_menu(
                    item(admin ? "Make member" : "Make admin", admin ? "member" : "admin", a.name),
                    item(a.disabled ? "Enable" : "Disable", a.disabled ? "enable" : "disable", a.name),
                    DOM.div(; class = "bt-menu-sep"),
                    item("New password", "password", a.name),
                    item("New authenticator", "authenticator", a.name;
                         ask = "Replace the authenticator of $(a.name)? The codes of the old one stop working."),
                    DOM.div(; class = "bt-menu-sep"),
                    item("Remove", "remove", a.name; danger = true, ask = "Remove the account $(a.name)?");
                    title = "Actions for $(a.name)"); class = "bt-admin-menu-cell");
                class = a.disabled ? "bt-account-off" : "", dataAccount = a.name)
        end
        DOM.table(DOM.tr(DOM.th("Account"), DOM.th("Groups"), DOM.th("Role"), DOM.th("")),
                  rows...; class = "bt-admin-table bt-accounts-table")
    end
    return DOM.div(
        DOM.div(DOM.h2("Accounts"); class = "bt-section"),
        DOM.div(table,
                DOM.div(DOM.button("Add account…"; class = "bt-btn bt-btn-sm bt-add-account",
                                   onclick = js"event => $(adding).notify(true)"),
                        login_codes_button(auth.config, session);
                        class = "bt-admin-form"),
                admin_line(secret, "bt-admin-secret"),
                admin_line(status, "bt-admin-status");
                class = "bt-card"),
        add_form)
end

# Without mail, Authelia writes what it would have sent to a file on the server:
# notices about new devices, and the rare one-time code that confirms who someone
# is (the server registers everyone's authenticator, so adding a device normally
# needs none). Admins read it here.
login_codes_button(cfg::ProxyConfig, session::Bonito.Session) =
    cfg.smtp ? nothing : login_codes_button(notifications_file(cfg), session)

function login_codes_button(file::AbstractString, session::Bonito.Session)
    is_open = Observable(false)
    return DOM.div(
        DOM.button("Authelia's messages"; class = "bt-btn bt-btn-sm bt-btn-secondary",
                   title = "What Authelia would have mailed; this server sends no mail",
                   onclick = js"event => $(is_open).notify(true)"),
        # Read on every open: it is the latest that matters.
        modal(session, is_open, "Authelia's messages") do
            text = isfile(file) ? read(file, String) : ""
            DOM.div(
                DOM.div("What Authelia would have mailed (this server sends no mail): notices " *
                        "about new devices, and now and then a one-time code someone needs to " *
                        "confirm who they are. Pass that on to the person it names.";
                        class = "bt-admin-muted"),
                DOM.pre(isempty(strip(text)) ? "Nothing yet." : text; class = "bt-admin-pre"))
        end)
end

invites_section(::OpenAuth, session::Bonito.Session, state::ServerState) = DOM.div()

function invites_section(::LoginAuth, session::Bonito.Session, state::ServerState)
    status = Observable("")
    link = Observable("")
    groups = Observable("")
    days = Observable("7")
    create = Observable(false)
    revoke = Observable("")
    on(session, create) do _
        admin_action!(status, () -> begin
            n = tryparse(Int, strip(days[]))
            (n === nothing || n < 1) && error("valid for: a number of days, at least 1")
            link[] = create_invite!(state, parse_groups(groups[]); valid_for = Day(n))
            "invite created; send the link to one person"
        end)
    end
    on(session, revoke) do id
        isempty(id) && return
        admin_action!(status, () -> revoke_invite!(state, id) ? "invite revoked" : "the invite was already gone")
    end
    table = map(session, state.invites) do invites
        open = sort!([i for i in values(invites) if i.expires > now(UTC)]; by = i -> i.created)
        isempty(open) && return DOM.div("No open invites."; class = "bt-admin-muted")
        rows = map(open) do i
            DOM.tr(DOM.td(i.created_by),
                   DOM.td(!isempty(i.account) ? "sets up $(i.account)" : isempty(i.groups) ? "member" : join(i.groups, ", ")),
                   DOM.td(Dates.format(i.created, "yyyy-mm-dd HH:MM")),
                   DOM.td(Dates.format(i.expires, "yyyy-mm-dd HH:MM")),
                   DOM.td(DOM.button("Revoke"; class = "bt-btn bt-btn-sm bt-btn-secondary",
                                     onclick = js"event => $(revoke).notify($(i.id))")))
        end
        DOM.table(DOM.tr(DOM.th("Invited by"), DOM.th("Groups"), DOM.th("Created (UTC)"),
                         DOM.th("Expires (UTC)"), DOM.th("")), rows...; class = "bt-admin-table")
    end
    return DOM.div(
        DOM.div(DOM.h2("Invites"); class = "bt-section"),
        DOM.div(
            DOM.div("An invite link lets one person create their own account; they get " *
                    "their password on the page it opens.";
                    class = "bt-admin-muted"),
            DOM.div(DOM.span("Groups"; class = "bt-admin-muted"),
                    # `admins` is offered here: the invite then makes an admin.
                    map(session, state.accounts) do _
                        chosen = String[strip(g) for g in split(groups[], ',') if !isempty(strip(g))]
                        group_picker(vcat(pickable_groups(state), "admins"), chosen,
                                     js"list => $(groups).notify(list.join(', '))";
                                     empty = "member", allow_new = true)
                    end,
                    DOM.label("valid for ", DOM.input(type = "text", value = days, size = 3,
                              oninput = js"event => $(days).notify(event.target.value)"), " days"),
                    DOM.button("Create invite link"; class = "bt-btn bt-btn-sm",
                               onclick = js"event => $(create).notify(true)");
                    class = "bt-admin-form"),
            admin_line(link, "bt-admin-secret"),
            admin_line(status, "bt-admin-status"),
            table;
            class = "bt-card"))
end

"""
    adapters_section(session, state)

Which agent adapters workers keep installed, at which versions ("latest", or a
version), on which Node ("lts", a major, or a version). Saving sends the change to
every connected worker; each installs it once no chat runs there.
"""
function adapters_section(session::Bonito.Session, state::ServerState)
    spec = state.harness_spec[]
    spec === nothing && return DOM.div()
    status = Observable("")
    node = Observable(String(spec["node"]))
    packages = Dict{String,Observable{String}}(String(k) => Observable(String(v))
                                               for (k, v) in spec["packages"])
    save = Observable(false)
    on(session, save) do _
        admin_action!(status, () -> begin
            new = Dict{String,Any}("node" => String(strip(node[])),
                                   "packages" => Dict{String,Any}(k => String(strip(o[])) for (k, o) in packages))
            (isempty(new["node"]) || any(isempty, values(new["packages"]))) &&
                error("every version needs a value: \"latest\" or a version")
            set_harness_spec!(state, new)
            "saved; connected workers install it once no chat runs there"
        end)
    end
    row(label, obs) = DOM.div(DOM.span(label; class = "bt-settings-title"),
                              DOM.input(type = "text", value = obs,
                                        oninput = js"event => $(obs).notify(event.target.value)");
                              class = "bt-admin-form")
    return DOM.div(
        DOM.div(DOM.h2("Agent adapters"); class = "bt-section"),
        DOM.div(
            DOM.div("Workers install these themselves, with a private Node, and update them " *
                    "while no chat runs. \"latest\" follows the npm registry.";
                    class = "bt-admin-muted"),
            row("Node", node),
            (row(k, packages[k]) for k in sort!(collect(keys(packages))))...,
            DOM.button("Save"; class = "bt-btn bt-btn-sm", onclick = js"event => $(save).notify(true)"),
            admin_line(status, "bt-admin-status");
            class = "bt-card"))
end

"""
    worker_sharing_row(auth, session, state, worker_id)

Behind the proxy, on a worker's card: the groups it is shared with, editable by
whoever manages it.
"""
worker_sharing_row(::OpenAuth, session::Bonito.Session, state::ServerState, worker_id::String) = DOM.div()

function worker_sharing_row(::LoginAuth, session::Bonito.Session, state::ServerState, worker_id::String)
    w = get(state.workers[], worker_id, nothing)
    (w === nothing || !can_manage(state, w)) && return DOM.div()
    status = Observable("")
    groups = Observable(join(w.shared_with, ", "))
    on(session, groups) do text
        admin_action!(status, () -> begin
            share_worker!(state, worker_id, parse_groups(text))
            isempty(strip(text)) ? "not shared" : "shared"
        end)
    end
    # Re-drawn when accounts change, so a group made since is on the list. The
    # sharing itself is not an account change, so an open list stays open.
    picker = map(session, state.accounts) do _
        current = get(state.workers[], worker_id, w).shared_with
        # An admin may share with a group nobody is in yet; a member only with theirs.
        group_picker(pickable_groups(state), current, js"list => $(groups).notify(list.join(', '))";
                     empty = "nobody", allow_new = is_admin(state))
    end
    return DOM.div(
        DOM.span("Shared with"; class = "bt-admin-muted",
                 title = "Members of these groups start chats here, which run as this machine's user."),
        picker,
        DOM.span(status; class = "bt-admin-status"), AdminStyles;
        class = "bt-admin-form bt-worker-sharing")
end
